### ISSUE TITLE
[FEATURE]: <Add Team section>

### ISSUE THREAD

**Issue by yashsehgal** [WeMakeDevs/wemakedevs#10]
To create a team members section as shown in the design screenshot below
<img width="1470" alt="Screenshot 2022-10-14 at 8 59 02 AM" src="https://user-images.githubusercontent.com/62352288/195755864-110ec9cb-9b6a-4270-9887-004c4a0b386f.png">

**Comment by abitsalihu** [comment]
Hey @yashsehgal, I would like to help with his issue. :)

**Comment by karankartikeya** [comment]
Hey, @yashsehgal Can I work on this issue??

**Comment by AnuragThePathak** [comment]
@karankartikeya only members are working on the first version.

**Comment by karankartikeya** [comment]
Sure @AnuragThePathak. Thanks for the info. Looking forward to contributing.

**Comment by maddy020** [comment]
Can I work on this issue?

**Comment by abhiraj-ku** [comment]
hey is anyone working on this
