### ISSUE TITLE
[bug] Links not updated.

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [WeMakeDevs/wemakedevs#101]
### Describe the bug

Recently, the Links of the website are updated but links of the buttons are still not.
![bug](https://user-images.githubusercontent.com/91469717/199775811-bfb82477-653a-4383-8e06-38f3a61743c1.jpg)
![image](https://user-images.githubusercontent.com/91469717/199775914-5e8ee7e1-ac48-4ca1-a935-f652be3b8b88.png)

**Comment by Lakshay-Pruthi** [comment]
I would like to work on this issue.

**Comment by maddy020** [comment]
Issue has been resolved 
Please merge this

**Comment by maddy020** [comment]
Hi @AnuragThePathak  I have solved the issue 
Please reply when will you merge my PR
