### ISSUE TITLE
Link to this page is not working[bug]

### ISSUE THREAD

**Issue by Sajiyah-Salat** [WeMakeDevs/wemakedevs#102]
### Describe the bug

When we try to open the courses it not working
PS: I am using ubuntu and chrome as a browser

### To Reproduce

Go to https://commclassroom.org/course
click on the courses

### Expected Behavior

It should take us to respective course page

### Screenshot/ Video
![Screenshot from 2022-11-04 07-11-44](https://user-images.githubusercontent.com/109643863/199867746-6265cdb5-3b82-446a-b161-c40a82f8c6f2.png)

**Comment by vishal-codes** [comment]
Hey @AnuragThePathak @Sajiyah-Salat  is this issue still valid, because I found that the link(https://commclassroom.org/course) is unreachable.

**Comment by Sajiyah-Salat** [comment]
I think it's not valid now as they changed the name and that makes the difference
