### ISSUE TITLE
Add a hover effect on navbar items and roadmap cards.

### ISSUE THREAD

**Issue by SaadAnsari17** [WeMakeDevs/wemakedevs#121]
### What would you like to share?

Add a hover effect on navbar items and roadmap cards.

**Comment by shaikahmadnawaz** [comment]
Can I start working on this Issue?

**Comment by SaadAnsari17** [comment]
> Can I start working on this Issue?

A PR has already been made to resolve this issue.

**Comment by shaikahmadnawaz** [comment]
Okay, Thank you for your response. 🙌
