### ISSUE TITLE
Adding Dark Mode to the website[feat]

### ISSUE THREAD

**Issue by prnvtripathi** [WeMakeDevs/wemakedevs#129]
### Would you like to have a new feature? Please describe.

Adding a toggle button to get the website in dark mode.

### How would this feature be beneficial for the project

By adding this feature we'll get the Dark Mode for the website and it'll look better with it

**Comment by prnvtripathi** [comment]
Hey, @AnuragThePathak please assign me the issue, I've started working on it.

**Comment by AnuragThePathak** [comment]
Hey, @prnvtripathi I'm sorry to inform you that it's not going to be implemented anytime soon. As general advice, I would suggest you not start working on a feature directly without consulting maintainers.

**Comment by prnvtripathi** [comment]
Ok, that's totally fine.
