### ISSUE TITLE
Adding style to the cards in courses section

### ISSUE THREAD

**Issue by prakharpants** [WeMakeDevs/wemakedevs#137]
### Would you like to have a new feature? Please describe.

The cards of the course content in courses section does not look good right now. They have no padding and the border is also very strict.It is not in sync with the above header section which makes this page look really unfinished.Styling it would be really good.

### How would this feature be beneficial for the project

It will really uplift the overall looks and user experience of the website specially of the courses section which is imho one of the important sections of the website.

### Additional context

![image](https://user-images.githubusercontent.com/83853518/202888531-739101ec-51c6-444d-9453-f757917ac695.png)

**Comment by prakharpants** [comment]
Hey, @AnuragThePathak please assign me the issue I have already made some changes and made a pullrequest I apologize if I have broken any protocol this is my first time contributing to an open source project.

**Comment by tejash023** [comment]
Hi, Can I work on this? I can add good box shadow with hover effect. Let me know.
