### ISSUE TITLE
WeMakeDevs website

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#142]
Home page (each main point is a section, think of it like a collection of rows)

- [x] Header
    - [x] Courses
    - [x] Mentorship
    - [x] Events
    - [x] Content
    - [x] Join
    - [x] Partner
- [x] About
    - [x] Number stats
- [x] [Courses](https://github.com/WeMakeDevs/courses)
    - [x] "Our students work"
    - [x] Testimonials i.e. Tweets
- [x] [Mentorship](https://github.com/WeMakeDevs/roadmaps)
- [x] [Events](https://github.com/WeMakeDevs/events)
    - [x] #332
- [x] Content
    - [x] [Podcast](https://www.youtube.com/playlist?list=PL9gnSGHSqcnqwmKYZ5rHuzqe32Di47KMr)
    - [x] [Blogs](http://blog.wemakedevs.org)
- [x] Join our community
    - [x] [Telegram](https://t.me/WeMakeDevs)
    - [x] [Discord](https://discord.com/invite/wemakedevs)
    - [x] #330
- [x] #331
- [x] Partner with us
    - [x] Just add an email here to kunal@wemakedevs.org
    - [x] #333
- [x] Footer

**Comment by tejash023** [comment]
Hi, Can I work on this?

**Comment by sboy99** [comment]
Hey I would love to become a contributor for this changes. Would I be able to do so?

**Comment by hargunrana** [comment]
hey there, i would like to contribute with the front end for wemakedevs....
looking forward

**Comment by sarthakjdev** [comment]
Hey 
I hope you people are doing well.
I want to work on the development of this site.
May I know the section I can contribute to, I can see many areas mentioned here. 
Is there any design framed for the site?

**Comment by abheektripathy** [comment]
Would like to contribute, can integrate some 3d stuff (using three.js) as well to make something aesthetic.

**Comment by manojkrishnak** [comment]
Hey @kunal-kushwaha, I would like to contribute to this website. Can you assign me too, also is there any platform where you are discussing on the roadmap items?

**Comment by J0SAL** [comment]
Hey @kunal-kushwaha, I would like to work on this website

**Comment by ManishBisht777** [comment]
Hi @kunal-kushwaha its good to know which person is doing which part/section so other can work accordingly

**Comment by abhishekrd** [comment]
Heyy, I would love to contribute in this website. I always like to make the UI clean and aesthetic which really impacts the overall experience of the website. @kunal-kushwaha Please assign me!

**Comment by kunal-kushwaha** [comment]
@abhishekrd you can make a PR with UI changed

**Comment by ManishBisht777** [comment]
This is my first time working on Figma
here is my idea to improve the current landing page (I had to figure out how to add icons though)
![image](https://user-images.githubusercontent.com/89926834/208945021-83e6aacd-ff80-40bd-af5c-deca3c5e778d.png)

here's the previous one
![image](https://user-images.githubusercontent.com/89926834/208945138-46d7dc8f-fc38-45df-801a-5e1e160e00df.png)


@kunal-kushwaha or maintainers any suggestions on this? I would love to implement it

**Comment by dubeysuraj864** [comment]
Hey kunal, I would like to contribute to this Website I have good skills in UI Development.

**Comment by anithasubramanian19** [comment]
I want to contribute in header part

**Comment by karanrao-github** [comment]
Thank you @kunal-kushwaha for this opportunity hope I would contribute something for this amazing community

**Comment by ManishBisht777** [comment]
Created a pull request #215 Regarding header improvement

**Comment by Prathyusha20a** [comment]
Hey Kunal, I want to work on this website

**Comment by tilltonystark** [comment]
> This is my first time working on Figma here is my idea to improve the current landing page (I had to figure out how to add icons though) ![image](https://user-images.githubusercontent.com/89926834/208945021-83e6aacd-ff80-40bd-af5c-deca3c5e778d.png)
> 
> here's the previous one ![image](https://user-images.githubusercontent.com/89926834/208945138-46d7dc8f-fc38-45df-801a-5e1e160e00df.png)
> 
> @kunal-kushwaha or maintainers any suggestions on this? I would love to implement it

Hey @ManishBisht777 !
I really appreciate you hard work.

But adding two primary buttons isn't a good practice. We should focus on one primary action we want from the user and the second one as secondary. Current UI isn't asthetic but it's kind of useful and usable.

I hope you'll come up with some more beautiful next time.

Thank you

**Comment by tilltonystark** [comment]
> Home page (each main point is a section, think of it like a collection of rows)
> 
> * [ ]  Header
>   
>   * [ ]  About
>   * [ ]  Courses
>   * [ ]  Mentorship
>   * [ ]  Events
>   * [ ]  Join
> * [ ]  About
>   
>   * [ ]  Number stats
> * [ ]  [Courses](https://github.com/WeMakeDevs/courses)
>   
>   * [ ]  "Our students work"
>   * [ ]  Testimonials i.e. Tweets
> * [ ]  [Mentorship](https://github.com/WeMakeDevs/roadmaps)
> * [ ]  [Events](https://github.com/WeMakeDevs/events)
> * [ ]  FAQ
> * [ ]  Join
>   
>   * [ ]  Telegram
>   * [ ]  Discord
>   * [ ]  Newsletter
> * [ ]  Partner with us
> * [ ]  Footer
>   
>   * [ ]  Add socials links: Twitter, Instagram, LinkedIn, GitHub, YouTube, Email

Hey!
Do consider these points as well, if at all it sounds good to you.
[ ] Do you have photographs of the events. Adding real photos with little black overlay instead of stock photos will work amazing.
[ ] Do we have some sponsors in the past? It would be nice if we can mention in the website.
[ ] Also, ask for student's testimonial. Adding them will bring more value to the website.

**Comment by tilltonystark** [comment]
> Home page (each main point is a section, think of it like a collection of rows)
> 
> * [ ]  Header
>   
>   * [ ]  About
>   * [ ]  Courses
>   * [ ]  Mentorship
>   * [ ]  Events
>   * [ ]  Join
> * [ ]  About
>   
>   * [ ]  Number stats
> * [ ]  [Courses](https://github.com/WeMakeDevs/courses)
>   
>   * [ ]  "Our students work"
>   * [ ]  Testimonials i.e. Tweets
> * [ ]  [Mentorship](https://github.com/WeMakeDevs/roadmaps)
> * [ ]  [Events](https://github.com/WeMakeDevs/events)
> * [ ]  FAQ
> * [ ]  Join
>   
>   * [ ]  Telegram
>   * [ ]  Discord
>   * [ ]  Newsletter
> * [ ]  Partner with us
> * [ ]  Footer
>   
>   * [ ]  Add socials links: Twitter, Instagram, LinkedIn, GitHub, YouTube, Email

I guess WeMakeDevs have a newsletter as well. 
Just a suggestion if we can add "subscribe to the newsletter" as a CTA in the hero section.

**Comment by ManishBisht777** [comment]
> > This is my first time working on Figma here is my idea to improve the current landing page (I had to figure out how to add icons though) ![image](https://user-images.githubusercontent.com/89926834/208945021-83e6aacd-ff80-40bd-af5c-deca3c5e778d.png)
> > here's the previous one ![image](https://user-images.githubusercontent.com/89926834/208945138-46d7dc8f-fc38-45df-801a-5e1e160e00df.png)
> > @kunal-kushwaha or maintainers any suggestions on this? I would love to implement it
> 
> Hey @ManishBisht777 ! I really appreciate you hard work.
> 
> But adding two primary buttons isn't a good practice. We should focus on one primary action we want from the user and the second one as secondary. Current UI isn't asthetic but it's kind of useful and usable.
> 
> I hope you'll come up with some more beautiful next time.
> 
> Thank you

thanks for the suggestions @tilltonystark but between the 2 of them what could be the primary one because courses and youtube both seem equally important to me

**Comment by tilltonystark** [comment]
> 

Yeah I agree with you. Here actually none of them is a good CTA. First one is link to the YouTube channel and second one is link of a playlist.

I guess better he add subscribe button for his newsletter as a CTA rather than the playlist. Because most of his audience will visit website through his youtube channel or may be telegram. So, there is no point sending them back on his channel again.

**Comment by devhiteshk** [comment]
#326 

New Logo Added
