### ISSUE TITLE
[other] Rename label  `external contributor` 

### ISSUE THREAD

**Issue by ashwinexe** [WeMakeDevs/wemakedevs#144]
### What would you like to share?

Rename `external contributor` label to `contributor` or something alternative.
Reason: The term **external** may not be inclusive and welcoming to new and consistent contributors. We want to make sure everyone feels included while contributing to our community 🚀

**Comment by hasnainmakada-99** [comment]
Hey, @ashwinexe Can I work on this?

**Comment by AnuragThePathak** [comment]
@hasnainmakada-99 I am not getting how you are planning to do that but it can be changed by people having required privilege only.

**Comment by hasnainmakada-99** [comment]
> @hasnainmakada-99 I am not getting how you are planning to do that but it can be changed by people having required privilege only.

Ohh, I need privileges for that ?

**Comment by ashwinexe** [comment]
Hey @hasnainmakada-99 this is a team-only issue. If you'd like to contribute, consider other open issues or opening a new issue if you spot something! Thanks

**Comment by hasnainmakada-99** [comment]
Ok @ashwinexe No problem

**Comment by kaiwalyakoparkar** [comment]
Good point @ashwinexe, @AnuragThePathak please do the required :)
