### ISSUE TITLE
[bug] Broken link in footer of the homepage

### ISSUE THREAD

**Issue by Rishabh-Singh-Codes** [WeMakeDevs/wemakedevs#157]
### Describe the bug

The link for "Events" in the footer of homepage is wrong. 
Current: https://github.com/wemakedevs/eventst
Correct: https://github.com/wemakedevs/eventst

P.S. : I would like to contribute to this project. Please give access and guidance on how to go about it. 

### To Reproduce

1. Go to homepage

**Comment by arpitapandya** [comment]
Can you assign me to work on this issue?
