### ISSUE TITLE
Adding Hover function to the website [buttons]

### ISSUE THREAD

**Issue by Jayaditya-Contributor** [WeMakeDevs/wemakedevs#167]
### Would you like to have a new feature? Please describe.

Adding hover property to the buttons , hovering on them makes their bakground color white and text color indigo

### How would this feature be beneficial for the project

It adds a responsive feel to the client , and makes the expreince even better , it just adding a small touch

**Comment by Jayaditya-Contributor** [comment]
Hey this is my first time opening an issue and I learned frontend development recently , and i was exploring github and found your awesome website

**Comment by Rishav1707** [comment]
Which button??
Navbar button or Courses, Events, Roadmaps button.
@Jayaditya-Contributor

**Comment by Rishav1707** [comment]
Anyone is there or not?? @Jayaditya-Contributor
