### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Spyder15** [WeMakeDevs/wemakedevs#169]
### Describe the bug

The website is still not responsive for some devices.

### To Reproduce

Use the viewing option of iphone XR, Galaxy S20 ultra or in any mobile device etc.. in inspect elements.

### Expected Behavior

no responsive

### Screenshot/ Video

<img width="286" alt="image" src="https://user-images.githubusercontent.com/97145602/205520516-3a894b63-673e-4653-b263-a613a7e2210f.png">

### Additional context

no responsive, in partner page page..

**Comment by Spyder15** [comment]
Responsiveness issue on mobile view

**Comment by AnuragThePathak** [comment]
Duplicate of #166
