### ISSUE TITLE
GitHub action build docker image and push to DockerHub or any container registry

### ISSUE THREAD

**Issue by AnuragThePathak** [WeMakeDevs/wemakedevs#19]
Create a GitHub action to build a docker image and push it to DockerHub or any container registry on release events.

**Comment by Dev-Arhaan** [comment]
HI, I'm interested in learning and creating a CI/CD pipeline with Github Action. I think I know enough yaml to do a good job here.

I'd be interested in talking to someone to know more about What and How can I write the YAML file in a good manner.

**Comment by AnuragThePathak** [comment]
@Dev-Arhaan kindly pick something that is unassigned. Kaiwalya is already working on it.
