### ISSUE TITLE
Adding a light mode to the website[feat]

### ISSUE THREAD

**Issue by prnvtripathi** [WeMakeDevs/wemakedevs#191]
### Would you like to have a new feature? Please describe.

As I'm watching the website it only consists of normal dark mode, i would like to work on and make a light mode for the website.

### How would this feature be beneficial for the project

Having two modes in which website's shown gives more freedom to users to use it in whatever mode possible

**Comment by vrindavan** [comment]
Light/Dark/System I guess?
