### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by anaskhan28** [WeMakeDevs/wemakedevs#193]
### Describe the bug

The button text is not responsive  and it should be in the center while adjusting or in different screen sizes

### To Reproduce

1 Go to 'https://wemakedevs.org/'
2.  Click on inspect 
3. check the responsiveness of a button text

### Expected Behavior

The text should be in the center and it  should occupies the space as the parent 

### Screenshot/ Video

![Screenshot_20221211_145244](https://user-images.githubusercontent.com/87796038/206895950-a56156f3-c56e-47ce-a567-8c749dacf7fa.png)

### Additional context

Improvement:
 It improves the overall UI and UX of the website.

**Comment by anaskhan28** [comment]
but it still not showing on the website.

**Comment by Rishav1707** [comment]
Because the issue #188  is not merged yet... @anaskhan28
