### ISSUE TITLE
[feat] - Sticky Navbar

### ISSUE THREAD

**Issue by Safnaj** [WeMakeDevs/wemakedevs#201]
### Would you like to have a new feature? Please describe.

Makes the navbar sticker so it ill be available through out the page.

### How would this feature be beneficial for the project

Easy navigation

**Comment by Rishav1707** [comment]
Shall I work on this issues? @AnuragThePathak

**Comment by vrindavan** [comment]
Prefer a normal bar or a hamburger menu?
