### ISSUE TITLE
[bug] About us cards could use centered text, it looks a bit off with text shifted left.

### ISSUE THREAD

**Issue by vrindavan** [WeMakeDevs/wemakedevs#203]
### Current:
![image](https://user-images.githubusercontent.com/50140643/208923206-e6c9818c-f08c-4267-a3e5-e4cfc3bd1faf.png)

### After:
![image](https://user-images.githubusercontent.com/50140643/208923404-ad5cdfdc-223c-4c31-8ada-ea23f7243d70.png)

Similar to #137 

## Fix

Just `text-align: center` for about_card.

**Comment by AnuragThePathak** [comment]
As a word of advice, one should add after part in the PR only.
