### ISSUE TITLE
[feat]Enhancement of the webpage's Main Navbar to a responsive one.

### ISSUE THREAD

**Issue by Sharath-1517** [WeMakeDevs/wemakedevs#206]
### Would you like to have a new feature? Please describe.

Zoom in transition for the navbar content (Home, Courses, Roadmaps, etc.).

### How would this feature be beneficial for the project

By adding this the navigation bar will get a responsive interface.

### Additional context

![GIF](https://user-images.githubusercontent.com/111525679/208957695-3cf1378d-af10-40f3-b1e5-0732fff0c632.gif)

**Comment by Sharath-1517** [comment]
Hello, Can I make a PR making few several changes in CSS to make this attractive interface feature for our website. Requesting for checks.
Thank you.

**Comment by Aadarsh805** [comment]
Please name issues properly @Sharath-1517

**Comment by Sharath-1517** [comment]
@Aadarsh805 Hello adarsh, So basically our main website currently is having the navbar in classic style. What I have suggested is that if we add those two additional css lines there will be a reactive navbar as I have attached the small video above in which I have added the transform and transition css properties for it using the chrome webpage editor.

**Comment by AnuragThePathak** [comment]
You don't need to right in message update title and description only. And practice writing in a formal way.

**Comment by Sharath-1517** [comment]
@Aadarsh805 Is it appliable, the current title of the issue or is there any other changes to be made?

**Comment by Sharath-1517** [comment]
Thank you for your information @AnuragThePathak I will note this and update it accordingly.

**Comment by AnuragThePathak** [comment]
Closed by #303
