### ISSUE TITLE
[bug] Improving responsiveness to the website

### ISSUE THREAD

**Issue by prnvtripathi** [WeMakeDevs/wemakedevs#207]
### Describe the bug

When using website on phone or narrow screen devices, the website isn't responsive enough. Improving responsiveness of the website.

### To Reproduce

1. Open the website on mobile screens, the website leaves blank space on the right

### Expected Behavior

All the divs should be center aligned and responsive.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/111558974/208959664-0bcb2505-53a8-4c5d-848c-be20a5c6d2c7.png)

![image](https://user-images.githubusercontent.com/111558974/208959721-8e782ddb-e910-497e-8823-9c7e5107c103.png)

**Comment by ArkaPrabhaChowdhury** [comment]
Hey, can I work on this? I have experience working with mobile websites.

**Comment by ManishBisht777** [comment]
The major reason for that in my opinion is hardcoded width and height and that too in px.

**Comment by Chandraprakash-Darji** [comment]
This is fixed
