### ISSUE TITLE
[bug] Incorrect Links in Navbar

### ISSUE THREAD

**Issue by ManishBisht777** [WeMakeDevs/wemakedevs#211]
### Describe the bug

![image](https://user-images.githubusercontent.com/89926834/209065427-59918d9e-185b-48ff-8602-29b0015ce64d.png)

the links in navbar is not doing what they meant for 
roadmap is taking us to mentorship
join is taking us to roadmap

### To Reproduce

go to the website click on roadmap or join

### Expected Behavior

they should perform what they are for

**Comment by FidalMathew** [comment]
@ManishBisht777 I would love to work on this issue. If you are not working on it, I would like to take this issue :)

**Comment by ManishBisht777** [comment]
sorry @FidalMathew I am not a maintainer so i can't really help you with this
