### ISSUE TITLE
[other] Navbar join button not working

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#219]
### Expected Behaviour

https://user-images.githubusercontent.com/97666287/209272027-e86a0a0b-93ea-4ae1-b669-550c2bb421ea.mp4

**Comment by hiteshvijayhv** [comment]
What is the expected behaviour? Should it redirect it to the discord channel?

**Comment by Rishav1707** [comment]
I am facing some issues while committing the changes. Can anyone tell me what is the problem?


![Commit](https://user-images.githubusercontent.com/97666287/209271884-31f1230c-c4ee-4c59-8f01-77fda37e2aef.png)

**Comment by Chandraprakash-Darji** [comment]
Let me look on this error. We have not faced any error yet

**Comment by Chandraprakash-Darji** [comment]
For now add `endOfLine: 'auto',` to your `.prettierrc.js` it will fix the error. Don't push the `.prettierrc.js`. We will update the file soon

**Comment by Rishav1707** [comment]
> For now add `endOfLine: 'auto',` to your `.prettierrc.js` it will fix the error. Don't push the `.prettierrc.js`. We will update the file soon

After adding `endOfLine: 'auto',` in `.prettierrc.js`, this error is showing

![error](https://user-images.githubusercontent.com/97666287/209365609-6acc92dd-7821-4a3a-bb83-bd382917a902.png)

**Comment by Chandraprakash-Darji** [comment]
It is fixed everything
