### ISSUE TITLE
[bug] Social Icons appear very low resolution icons on desktop version.

### ISSUE THREAD

**Issue by hiteshvijayhv** [WeMakeDevs/wemakedevs#220]
### Describe the bug

Social Icons appear very low resolution icons on desktop version.

### To Reproduce

1. on https://wemakedevs.org/ website scroll to the end.

The appearance is like this. 
![Screenshot_20221223_085503](https://user-images.githubusercontent.com/46933160/209265210-5ec4ee8e-23c5-48cb-b0cb-138eeb5a048c.png)

### Expected Behavior

It should have better resolution so that it looks better on bigger screens.

**Comment by hiteshvijayhv** [comment]
I will make a PR

**Comment by Chandraprakash-Darji** [comment]
They are svg, from font awesome that is not possible that svg can lose there resolution

**Comment by Chandraprakash-Darji** [comment]
It is working perfect on our side
