### ISSUE TITLE
[bug] nonresponsive links

### ISSUE THREAD

**Issue by divyanshchahar** [WeMakeDevs/wemakedevs#224]
### Describe the bug

The following links are nonresponsive i.e. they do not change the URL or navigate to or scroll to nowhere.

- [ ] Discord link inside JOIN OUR COMMUNITY section at the bottom of the page (in desktop mode)
- [ ]  Telegram link inside JOIN OUR COMMUNITY section at the bottom of the page (in desktop mode)
- [ ] All the links inside the menu which expand after clicking on the button in the top navigation bar (mobile screens only)

### To Reproduce

- visit the website from desktop
- visit the website from mobile (or use the responsive mode of your browser)

**Comment by Chandraprakash-Darji** [comment]
I will look into it. Thanks for creating the issue @divyanshchahar
