### ISSUE TITLE
[other] Fix width of horizontal lines of Home Components

### ISSUE THREAD

**Issue by shivam-sharma7** [WeMakeDevs/wemakedevs#228]
### What would you like to share?

Fix width of horizontal lines.

components are-
- About us
- Cards
- Courses
- Events
- Mentorship

 visit Page- https://wemakedevs.org/

### Additional information

 
![Screenshot (19)](https://user-images.githubusercontent.com/91419219/209319047-d323d5a3-d87a-4a47-8122-cd125efdb03c.png)

**Comment by Chandraprakash-Darji** [comment]
@shivam-sharma7 Thanks for sharing it. I will look into it

**Comment by AnuragThePathak** [comment]
Closing as included in #230
