### ISSUE TITLE
[bug] Education, events, and mentorship card is not responsive in mobile Screen

### ISSUE THREAD

**Issue by AbhiPatel10** [WeMakeDevs/wemakedevs#233]
### Describe the bug

In Mobile view Education, events, and mentorship card is not responsive

### To Reproduce

Open in mobile view.

### Expected Behavior

All Cards should be responsive in Mobile view.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/76242769/209428465-f22aaf91-7988-4ca6-8344-c9a15bcdea9e.png)

![image](https://user-images.githubusercontent.com/76242769/209428467-86b3ae3c-69b5-4c04-9715-7603d649f9d4.png)

![image](https://user-images.githubusercontent.com/76242769/209428469-276e6f82-607f-4b8f-b8da-e8ed635beb89.png)

### Additional context

Please assign me, I Would like to work on this issue.

**Comment by Chandraprakash-Darji** [comment]
It was in old website not in new one

**Comment by AbhiPatel10** [comment]
> It was in old website not in new one

Okay

**Comment by AbhiPatel10** [comment]
I have Change Issue please check it and assign this to me.

**Comment by Chandraprakash-Darji** [comment]
> I have Change Issue please check it and assign this to me.

This is also fixed just PR is merge is left it will be done ny today
