### ISSUE TITLE
[bug] Links inside Hamburgur Menu are not working properly

### ISSUE THREAD

**Issue by karanrao-github** [WeMakeDevs/wemakedevs#246]
### Describe the bug

![fldMQxmBO5](https://user-images.githubusercontent.com/75921126/209434461-1134abd2-6307-4ea1-adf8-368d1ae043af.gif)

**Page not loading after you select an option from ham burger menu**

> **NOTE:** Url is updating

- To make it work a user has to refressh the page.

### To Reproduce

1. Open WeMakeDevs.org website on Samrtphone browser or use smartphone view on your desktop browser
2. Tap on Ham Burger menu icon to open **Menu**
3. Tap on any of the Options present inside the Ham Burger Menu.
4. Refresh the page 

### Expected Behavior

Taping on option should scroll down or up to the respective page

**Comment by Chandraprakash-Darji** [comment]
@karanrao-github what do you think where error can be?

**Comment by karanrao-github** [comment]
Correct me if I am wrong, but I guess it javascript

**Comment by FrozenHearth** [comment]
https://user-images.githubusercontent.com/27160715/209565470-2d64996c-868f-4546-b047-2e85bc019028.mov

The error seems to be here. In Header > Index.jsx file. 
`setOpen is not a function`

**Comment by dharmjoshi236** [comment]
The error is basically, when we are clicking the nav item in mobile view, the header class is not updating. We need some re-render function which will re-render the nav on the scrollTop value.

Made the function for re-render and now its working..

Below is the video for the same....

https://user-images.githubusercontent.com/60209531/210181502-3cd85056-fc1d-40a0-bd7f-5e1efdf89d7d.mp4

**Comment by FrozenHearth** [comment]
@dharmjoshi236 Please feel free to raise a PR for the same.
