### ISSUE TITLE
[bug] - Giving the margin to Navbar from top

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#252]
### Describe the bug

There should be a margin from the top for Navbar it will improve the UX

Before:
![image](https://user-images.githubusercontent.com/67385503/209448867-fe630b73-940a-4b39-b4af-539d85c22179.png)

After:
![image](https://user-images.githubusercontent.com/67385503/209448895-0de0f8b6-2db9-4908-8a50-35be8bcbd43d.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/67385503/209448895-0de0f8b6-2db9-4908-8a50-35be8bcbd43d.png)

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/67385503/209448867-fe630b73-940a-4b39-b4af-539d85c22179.png)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue.

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak assign the issue to @UtkarshMishra12

**Comment by AnuragThePathak** [comment]
@UtkarshMishra12 go ahead
