### ISSUE TITLE
[bug] - The Amazon logo is not visible, It needs to be changed as per the theme.

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#253]
### Screenshot/ Video

![image](https://user-images.githubusercontent.com/67385503/209449048-f2acf97d-886f-443d-aa86-6f33309e7004.png)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue

**Comment by Chandraprakash-Darji** [comment]
@UtkarshMishra12 I working on it already

**Comment by FrozenHearth** [comment]
@Chandraprakash-Darji Can we also add a bit of top spacing above "Our Students Work At" text? Or is that already done in another PR?

**Comment by Chandraprakash-Darji** [comment]
It is been fixed in the PR #274
