### ISSUE TITLE
[bug] - Boxes are not responsive (Education, Events & Mentorship) from 768px to 870px

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#254]
### Describe the bug
Boxes are not responsive (Education, Events & Mentorship) from 768px to 870px 

Before:

https://user-images.githubusercontent.com/67385503/209449274-06d7e5ae-ebcc-4bf8-a6f1-592aa13099e1.mp4

After:

https://user-images.githubusercontent.com/67385503/209449291-3b8d450c-3c82-498e-a8d4-a9b410faf68a.mp4

_No response_

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak Assign the @UtkarshMishra12
