### ISSUE TITLE
[bug] - Problem with the responsiveness of the Navbar 

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#255]
### Screenshot/ Video

https://user-images.githubusercontent.com/67385503/209449474-5478abff-30c6-43ad-8449-6d068e666851.mp4

**Comment by Chandraprakash-Darji** [comment]
Thanks for creating issue

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue
