### ISSUE TITLE
[bug] - No margin in the button (providing it will improve the UX)

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#256]
### Describe the bug

No margin in the button (providing it will improve the UX)

### Expected Behavior

![image](https://user-images.githubusercontent.com/67385503/209449722-dd208d4d-76b3-4e63-a27b-4be5ee04def1.png)

![image](https://user-images.githubusercontent.com/67385503/209449738-3e2b9f55-52be-4857-9742-da56036aeef3.png)

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/67385503/209449704-73126bc3-91c7-4a24-9b4f-c1000d299e4e.png)

![image](https://user-images.githubusercontent.com/67385503/209449728-fe7083ae-e1b9-4b11-8ffa-a86b8815ff28.png)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue

**Comment by UtkarshMishra12** [comment]
@Chandraprakash-Darji Can you please assign it to me?

**Comment by Chandraprakash-Darji** [comment]
@UtkarshMishra12 can you share the diff between the old one and expected? From my side, I guess both are the same.

**Comment by UtkarshMishra12** [comment]
@Chandraprakash-Darji The first two screenshots are after changes (see the margin between the buttons). The other two ss are before the changes (without margin)

**Comment by Chandraprakash-Darji** [comment]
@UtkarshMishra12 Gap between the buttons. ohh. I assign you
