### ISSUE TITLE
[bug] -  Typo (spelling of concept in the last box)

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#257]
### Screenshot/ Video

![image](https://user-images.githubusercontent.com/67385503/209449843-414cf014-1ba9-4cb8-944b-1716229adbe3.png)

**Comment by UtkarshMishra12** [comment]
Any new-comer raise your first PR 👀

**Comment by Chandraprakash-Darji** [comment]
That are actual tweets by the users

**Comment by UtkarshMishra12** [comment]
But we can correct it if there is any typo 👀 @Chandraprakash-Darji

**Comment by Chandraprakash-Darji** [comment]
we can

**Comment by Vishvsalvi** [comment]
May I contribute?
