### ISSUE TITLE
[bug] -  Wrong data in the card on hover.

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#259]
### Describe the bug

Wrong data in the card on hover. It should be 56k+ not 56+ 👀 

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/67385503/209450172-827a4628-7b52-449e-97b5-87f30c219e68.png)

**Comment by UtkarshMishra12** [comment]
A newcomer can raise their PR 👀 🚀

**Comment by SuperAayush** [comment]
Thank You for opening the issue, we still have to make some changes in the section as per issue number #142.

**Comment by UtkarshMishra12** [comment]
I would love to contribute to this issue #142. Let me know if I can contribute 😄 @SuperAayush

**Comment by Vishvsalvi** [comment]
`\fixed`
