### ISSUE TITLE
[bug] - Irregular border bottom at each heading 

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#260]
### Describe the bug

Irregular border bottom at each heading (some of the headings are provided in full bottom order whiles others are not).

### Expected Behavior

Rather than using the hard-coded single value for the border-bottom, it should be given according to the text size.

### Screenshot/ Video

https://user-images.githubusercontent.com/67385503/209450424-7f755bc4-ebc9-4ada-8ea5-a9fb15115249.mp4

**Comment by Chandraprakash-Darji** [comment]
Thanks for the issue @UtkarshMishra12

**Comment by Chandraprakash-Darji** [comment]
Anyone want to work on it `margin-block: 1.5rem` to hr

**Comment by UtkarshMishra12** [comment]
@Chandraprakash-Darji Actually, for every heading, we have to pick the bottom by the trial method. 👀 
So I would like to go for this one.

**Comment by Chandraprakash-Darji** [comment]
@UtkarshMishra12 Let someone else should come also

**Comment by AbhiPatel10** [comment]
Hey @Chandraprakash-Darji I Would like to work on this.

**Comment by Chandraprakash-Darji** [comment]
@AbhiPatel10 did you get the issue?

**Comment by AbhiPatel10** [comment]
Yes We need to make bottom border as per the text size.

**Comment by UtkarshMishra12** [comment]
@Chandraprakash-Darji I'm already working on this 👀

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji is this issue not fixed in #260 ?

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak I haven't get issue even now

**Comment by AbhiPatel10** [comment]
@Chandraprakash-Darji  That the Under line of every section Headers is constant we should make Them as compare to text size like this

Please Correct if i'm wrong @AnuragThePathak , @UtkarshMishra12 

![image](https://user-images.githubusercontent.com/76242769/210197533-f736e242-3d5a-4538-843e-128e0369350c.png)

![image](https://user-images.githubusercontent.com/76242769/210197538-503eba8e-1e1b-4d27-9eab-d0ed789fb1c4.png)

![image](https://user-images.githubusercontent.com/76242769/210197601-2f705638-e660-4e31-afae-377b413a6509.png)

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji I think they want the underlines at the bottom of the headings to cover the whole characters instead of covering a constant amount of characters only.

**Comment by UtkarshMishra12** [comment]
> @Chandraprakash-Darji I think they want the underlines at the bottom of the headings to cover the whole characters instead of covering a constant amount of characters only.

You are right @AnuragThePathak

**Comment by Chandraprakash-Darji** [comment]
> @Chandraprakash-Darji I think they want the underlines at the bottom of the headings to cover the whole characters instead of covering a constant amount of characters only.

@AnuragThePathak then it would not look consistent for all the heading 
Let's see what all maintainer says
