### ISSUE TITLE
[bug] -  Outdated Data for members count

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#261]
### Expected Behavior

It should be 56,000+

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/67385503/209450562-1b2a0a4e-009b-45bc-b567-cff53c0b07e9.png)

**Comment by UtkarshMishra12** [comment]
Newcomers 👀 🚀

**Comment by AbhiPatel10** [comment]
Hey @UtkarshMishra12 and @Chandraprakash-Darji  I Would like to work on this.
