### ISSUE TITLE
[bug] Our Students work at section not aliened well

### ISSUE THREAD

**Issue by AbhiPatel10** [WeMakeDevs/wemakedevs#267]
### Describe the bug

Our students work at section heading is stick to above section.

### To Reproduce

Go to OUR STUDENTS WORK AT Section

### Expected Behavior

Should give some padding from top as we given to other components.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/76242769/209464947-fd9398a2-d822-49a3-a310-02f3a96a7fc9.png)

### Additional context

Please assign this to me

**Comment by Chandraprakash-Darji** [comment]
I assign but make sure you there is consistent space as in other sections. Must check other sections of CSS too.
Possible the make all the logos white/gray for visibilty

**Comment by Chandraprakash-Darji** [comment]
Make the heading small case not the capitalize
