### ISSUE TITLE
[docs] Update Readme File

### ISSUE THREAD

**Issue by AbhiPatel10** [WeMakeDevs/wemakedevs#269]
### Category of documentation update

Readme.md

### Describe the change you think might work

Need to change Demo Screenshot as we have changed the Home main section.

Before :

![image](https://user-images.githubusercontent.com/76242769/209465971-fc651d19-6557-4a99-96fe-75decf31a7ba.png)

After:

![image](https://user-images.githubusercontent.com/76242769/209465951-79f417b3-aa97-414d-a07e-018e56909413.png)

We can Update about project content:

Before: 

"This is a community which provides free hands-on training in various fields of computer science and have an inclusive community focusing on a learn by doing approach."

After: 

"Our community provides a variety of FREE hands-on computer science training and workshops designed to help individuals develop practical skills through hands-on learning experiences. We are committed to fostering an inclusive and supportive environment where everyone can learn and grow. Our "learn by doing" approach means that you will have the opportunity to actively engage with the material and put your newly acquired skills into practice."

**Comment by AbhiPatel10** [comment]
Assign this task to me.

**Comment by AnuragThePathak** [comment]
Are you going to work on it? If not close it or I'll. It's not an important task for us anyway.
