### ISSUE TITLE
[feat] Adding Navigation dots HOC

### ISSUE THREAD

**Issue by AshuwinB** [WeMakeDevs/wemakedevs#275]
### Would you like to have a new feature? Please describe.

Want to add a Navigation dot. Each component will have its own set of navigation buttons. Each component will be wrapped with a higher order component to do so.

### How would this feature be beneficial for the project

This feature will make navigation much easier. It's a UI enhancement.

**Comment by AnuragThePathak** [comment]
More description needed, no one is getting what you wanna mean.

**Comment by Parvej2001** [comment]
@AshuwinB can u describe the issue in detail.
