### ISSUE TITLE
[bug] FAQ cards gap issue in mobile screens

### ISSUE THREAD

**Issue by siddhigate** [WeMakeDevs/wemakedevs#278]
### Describe the bug

- There is no gap between 2 sections of FAQ card groups in mobile screens

### To Reproduce

1. Go to the FAQ section
2. Open the screen for mobile screen sizes
3. There will be no gap between the third and the fourth card.

### Expected Behavior

- There should be a gap between the third and the fourth card in the FAQ section in mobile screens

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/80971056/209487456-92bb3c64-7cc4-45d8-8239-d5c033c14dcc.png)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by siddhigate** [comment]
> Shall I work on this issue?

Yes, you can. Assigning it to you.
