### ISSUE TITLE
[other] Add aliases for directory paths

### ISSUE THREAD

**Issue by FrozenHearth** [WeMakeDevs/wemakedevs#281]
### What would you like to share?

Right now, we are having to manually specify the directory path in this way: 
`import xyz from "../../../components/XYZComponent"`

With aliasing using jsconfig.json file, we can clean up the import syntax, and do something like, 
`import xyz from 'components/XYZComponent'`

Reference: https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases

**Comment by Chandraprakash-Darji** [comment]
@FrozenHearth there was `.jscondig` path alias. But it was not working it.
To work with we need to change webpack config as I have searched for. So the task is for later in the project.

**Comment by FrozenHearth** [comment]
@Chandraprakash-Darji Understood. Seems like Create React App doesn't support it. So one way to do it without ejecting CRA is to use this package: https://github.com/dilanx/craco

**Comment by Chandraprakash-Darji** [comment]
@FrozenHearth We will add later for now not.
