### ISSUE TITLE
Redirection Problem

### ISSUE THREAD

**Issue by jiyanpatil07** [WeMakeDevs/wemakedevs#283]
### Describe the bug

When we are on mentorship or event or any other page instead of the home page , If we click on the 'we make devs logo or the text' it should redirect us to home page and thats the issue here.

### Screenshot/ Video

[screen-capture.webm](https://user-images.githubusercontent.com/76421551/209776232-3e570355-ee8c-4aa2-ac52-1d957b3819f7.webm)

**Comment by PrashantIndurkar** [comment]
Got it i wanna work on this please assign this task to me I will fix this asap :)

**Comment by AnuragThePathak** [comment]
For now let us keep this issue in freeze as we already have a home item in the navbar.

**Comment by jiyanpatil07** [comment]
@AnuragThePathak Thank You
