### ISSUE TITLE
[bug] npm run dev

### ISSUE THREAD

**Issue by Vishvsalvi** [WeMakeDevs/wemakedevs#285]
### Describe the bug

There is no script in the package.json such as "dev"

### To Reproduce

Just follow the README.md installation process

### Expected Behavior

The application should run in the development mode.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/82429084/209903494-cf6a7b29-de1c-4c2e-b23d-ce8f8a0cd54c.png)

![image](https://user-images.githubusercontent.com/82429084/209903536-c3adb7ae-ba37-46d2-9be9-e4f2042cabdd.png)

### Additional context

Add the run dev in the script command or change the README.md installation steps.

**Comment by Chandraprakash-Darji** [comment]
There is a mistake in the documentation. The command is `npm run start`.

**Comment by maddy020** [comment]
Hey @Chandraprakash-Darji 
I woul like to work on this issue 
Please assign it to me
