### ISSUE TITLE
[docs] Wrong route for mentorship button in wemakedevs.org

### ISSUE THREAD

**Issue by ashikkabeer** [WeMakeDevs/wemakedevs#289]
### Category of documentation update

![Screenshot from 2022-12-31 06-17-21](https://user-images.githubusercontent.com/97529548/210120099-23e1e3bf-b680-418b-ad8f-617783d547d9.png)

this button returns https://www.youtube.com/@KunalKushwaha/playlists

### Describe the change you think might work

https://github.com/WeMakeDevs/roadmaps

**Comment by Rohitjakkam** [comment]
I want to work on this issue

**Comment by Rohitjakkam** [comment]
it is done from my side

**Comment by Rohitjakkam** [comment]
![Screenshot from 2022-06-07 01-16-12](https://user-images.githubusercontent.com/86354086/210149299-ec125285-b02c-4396-b425-cab2bdf1694d.png)

**Comment by Rohitjakkam** [comment]
![Screenshot from 2022-12-31 21-40-12](https://user-images.githubusercontent.com/86354086/210149312-3d03afa1-de4d-4f77-82ce-ec4502f737dd.png)
