### ISSUE TITLE
[bug] - Improving Navbar in mobile view

### ISSUE THREAD

**Issue by UtkarshMishra12** [WeMakeDevs/wemakedevs#292]
### Describe the bug

Currently, the navbar is not covering the entire width of the screen.

Now:
![image](https://user-images.githubusercontent.com/67385503/210172626-12eb885d-089f-424c-a235-81194f0555d6.png)

Desired:
![image](https://user-images.githubusercontent.com/67385503/210172633-4725f83d-c1f5-42a6-bb4a-a0fdad6bc6ed.png)

**Comment by AbhiPatel10** [comment]
Also Make  responsive Navbar in between 875px to 769px

![image](https://user-images.githubusercontent.com/76242769/210198671-5345e0f3-3179-43b2-b0fe-7cdb6b32e6ca.png)

**Comment by AbhiPatel10** [comment]
I think Center Align Looks Good To me What you say ? @Chandraprakash-Darji 

![image](https://user-images.githubusercontent.com/76242769/210199052-2564a619-be04-4700-a933-7745d5c3e651.png)
