### ISSUE TITLE
[bug] Blog Section Is not responsive

### ISSUE THREAD

**Issue by AbhiPatel10** [WeMakeDevs/wemakedevs#296]
### Describe the bug

Blog section is not responsive in Tablet view

### To Reproduce

View In tablet View

### Expected Behavior

All Cards Should be in Center 

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/76242769/210235872-1123ecea-0da3-4f27-8db1-054a4da9e0bd.png)

### Additional context

Please Assign this task to me.

**Comment by AnuragThePathak** [comment]
I tested it in brave, chrome and Firefox. The screenshot that you shared can't be produced, the items are taking full width.
