### ISSUE TITLE
[other] The podcast image should be changes

### ISSUE THREAD

**Issue by Vishvsalvi** [WeMakeDevs/wemakedevs#335]
### What would you like to share?

![image](https://user-images.githubusercontent.com/82429084/212810765-9e751a8f-7917-4af2-8841-ed6723ef4284.png)

The image used in podcast section doesn't actually represents podcast.
Better pictures like this can be used 
![Screenshot_20230116_220502](https://user-images.githubusercontent.com/82429084/212810969-712377a5-91b8-4b5a-b8db-77ccfb825688.png)

### Additional information

Use image generation AI such as Midjourney or Dall.e can be used.

**Comment by Chandraprakash-Darji** [comment]
@Vishvsalvi Thanks for the Issue. We are thinking to update every assets of the website. These you may thinking that are the dummy used.

**Comment by Chandraprakash-Darji** [comment]
@Vishvsalvi Thanks for the Issue. We are thinking to update every assets of the website. These you may thinking that are the dummy used.

**Comment by Vishvsalvi** [comment]
Can I provide some good images?

**Comment by Chandraprakash-Darji** [comment]
@Vishvsalvi Sure you can, Use copyright free images

**Comment by Vishvsalvi** [comment]
What is your opinion on this one? 

![image](https://user-images.githubusercontent.com/82429084/213624711-1a79c2b1-c303-4da3-a94a-93eec9e9fc40.png)

**Comment by AnuragThePathak** [comment]
Way to fancy ig?

**Comment by Vishvsalvi** [comment]
> Way too fancy ig?

Okk, will keep it simple

**Comment by AnuragThePathak** [comment]
Just an update: the image selection is being done by the team, and most probably they will push the changes.

**Comment by kunal-kushwaha** [comment]
this is done
