### ISSUE TITLE
[other] Potential Contributions for to Resolve Accessibility score 

### ISSUE THREAD

**Issue by Umayarz18** [WeMakeDevs/wemakedevs#336]
### What would you like to share?

I just did a quick accessibility test on your site using [Perfbuddy](https://perfbuddy.com/) and Chrome Lighthouse audit. Some areas can be improved and could be a great first issue/PR for new contributors. 

Based on the audit, here are some suggested changes by the audit:

- [ ] Buttons do not have an accessible name
![Screenshot (11)](https://user-images.githubusercontent.com/61628982/212811063-1962e121-a284-4c40-989e-ae56a0930e1a.png)
- [ ] `<frame>` or `<iframe>` elements do not have a title
- [ ] Links do not have a discernible name
![Screenshot (12)](https://user-images.githubusercontent.com/61628982/212811351-f45d59bc-dee0-4b64-b417-c82f5f5024e5.png)
- [ ] Background and foreground colors do not have a sufficient contrast ratio. (Seems to be flagging the purple text and the grey color for the buttons)
![Screenshot (13)](https://user-images.githubusercontent.com/61628982/212811632-aed6ae7d-0bdc-4b9a-a4e0-0a47196e5213.png)
- [ ] Lists do not contain only `<li>` elements and script supporting elements (`<script>` and `<template>`).
![Screenshot (14)](https://user-images.githubusercontent.com/61628982/212811791-f5368469-b22b-4db1-a5a6-9763331cb892.png)

These are very few tweaks and I think separating them into different issues would be a great first contribution for newer developers 😄. I can also tweak some of these as well or anything else involving accessibility.

### Additional information

The audit only caught any issues easily picked up through Lighthouse. A [hands-on accessibility audit](https://web.dev/how-to-review/) may be necessary to tackle more specific items.

**Comment by Chandraprakash-Darji** [comment]
@Umayarz18 Thanks for the Issue.

**Comment by VijayalakshmiGanesh** [comment]
Hi, I'm interested in contributing to this project. Would it be possible for me to work on this issue? I'm a beginner, but I would like to take this opportunity to learn and improve my skills. Please let me know if I can work on this. Thank you!

**Comment by Chandraprakash-Darji** [comment]
@VijayalakshmiGanesh Sure you can work on this. If you need any help then mention me

**Comment by VijayalakshmiGanesh** [comment]
Hi @Chandraprakash-Darji, For contrast issue, i have changed two colors. Please do let me know if can proceed with these color changes. 

First change:
![image](https://user-images.githubusercontent.com/104077094/219553788-ca450f46-ac9d-4c94-8139-bf61bbe9c61e.png)
Currently its using color - #7765ed

I have changed it to #A293F3 which looks like the below
![image](https://user-images.githubusercontent.com/104077094/219554146-3c8e04e6-b8e8-4cdd-b054-08a10e05c328.png)


Second change: This change almost changes the whole theme (purple) color of the website. Currently the website is using #5942e9. I tried two colors which almost match with the existing one. 

1. #443C90 
![image](https://user-images.githubusercontent.com/104077094/219554719-a79c520c-62de-4f11-a11b-36e6309e2de3.png)

2. #3D2EBD
![image](https://user-images.githubusercontent.com/104077094/219554960-b16472e6-7e2b-4a00-b7ef-99fb57eb3a45.png)

**Comment by Chandraprakash-Darji** [comment]
@VijayalakshmiGanesh just make the link dark and test on lighthouse. You can do by just removing the class `highlight--light`. This is util class you can found in the `util.css`

**Comment by VijayalakshmiGanesh** [comment]
> @VijayalakshmiGanesh just make the link dark and test on lighthouse. You can do by just removing the class `highlight--light`. This is util class you can found in the `util.css`

Removing highlight--light doesn't resolve the contrast issue.
![image](https://user-images.githubusercontent.com/104077094/219694496-d1bdfc1a-ca55-4df9-a17e-0144ef1aa680.png)

This is the darkest color i could find "#A293F3" resolving this issue.

**Comment by VijayalakshmiGanesh** [comment]
Opened the pull request. Kindly review it.
