### ISSUE TITLE
[feat] make Animating counter up stats 

### ISSUE THREAD

**Issue by hparashar27** [WeMakeDevs/wemakedevs#339]
### Would you like to have a new feature? Please describe.

the stats look much better if they are animation counter up stats 

before -

![chrome_akacUzHWxu](https://user-images.githubusercontent.com/96375055/213139910-684b8a96-b9b5-446c-abb3-14ebea103b84.png)
 
after -

https://user-images.githubusercontent.com/96375055/213140075-39c4c8d5-d1b3-42a1-85ac-d2a0c5adf529.mp4

**Comment by hparashar27** [comment]
if you think it will be better feature , then i can start working on it

**Comment by Chandraprakash-Darji** [comment]
@hparashar27 Good feature Brother

**Comment by Chandraprakash-Darji** [comment]
I am assigning you

**Comment by Chandraprakash-Darji** [comment]
try git pull

**Comment by hparashar27** [comment]
didn't worked , getting same error -
![Code_ygw7GXv4MJ](https://user-images.githubusercontent.com/96375055/213378044-5ad08cea-815e-466b-aff3-92b5fe444a08.png)

**Comment by ShimpiTejas** [comment]
is this solved ? , if not please assign it to me

**Comment by Chandraprakash-Darji** [comment]
@ShimpiTejas I have assigned you

**Comment by MaruthiKo** [comment]
Is this issue still open @Chandraprakash-Darji 
If yes I would like to work on it

**Comment by Chandraprakash-Darji** [comment]
@MaruthiKo yes iti is open. I have assigned you
