### ISSUE TITLE
[bug]Cards after event section is not maintaining equal height.

### ISSUE THREAD

**Issue by Debjyoti0404** [WeMakeDevs/wemakedevs#352]
###Cards after event section is not maintaining equal height.
After the event section on the website, the cards are not maintaining same heights.

### To Reproduce

Go after the event section.

### Expected Behavior

All cards should be in same heights.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/103656712/213515954-596cdadf-2edf-41c7-a046-c15f65f7bc4c.png)

**Comment by Chandraprakash-Darji** [comment]
@Debjyoti0404 this is twitter cards we can set their size. It depends on there content that is coming from Twitter.

**Comment by Debjyoti0404** [comment]
Oh, ok. Then I am closing the issue.
