### ISSUE TITLE
[feat]Added Faq's link in header 

### ISSUE THREAD

**Issue by shreyasri258** [WeMakeDevs/wemakedevs#354]
### Would you like to have a new feature? Please describe.

Added faq's link in the header in this PR  #353

<img width="960" alt="Screenshot_20230120_072948" src="https://user-images.githubusercontent.com/84087589/213619695-81bcd12a-f13b-468f-ad70-5d4a940a97b0.png">

**Comment by kunal-kushwaha** [comment]
not need, thank you
