### ISSUE TITLE
[feat] Overall events page

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#356]
### Would you like to have a new feature? Please describe.

- [ ] Header
- [ ] About
    - [ ] Stats about prizes, Tweet testimonials, and learnings.
- [ ] Ongoing events
- [ ] Past events
- [ ] Join
- [ ] Events related FAQ
- [ ] Partner
- [ ] Footer

**Comment by Chandraprakash-Darji** [comment]
On it

**Comment by ShimpiTejas** [comment]
Hey, Kunal This is the first time I am trying to contribute to open source, please assign me some good first issues to solve, and I will try my best to solve the problems..

**Comment by Chandraprakash-Darji** [comment]
@ShimpiTejas this issue is solved. You can find the good first issue in issue tab with the tag

**Comment by Chandraprakash-Darji** [comment]
@ShimpiTejas you can visit the <https://wemakedevs.org/> and find the issue there also

**Comment by Chandraprakash-Darji** [comment]
Solved: https://wemakedevs.org/events
