### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Sreejit-Sengupto** [WeMakeDevs/wemakedevs#359]
### Describe the bug

When navigating the site using links int the navbar and then when back button is clicked it scrolls back to the last visited section. Like if I click Courses link in the navbar it takes me to the courses section but when I click back button it scrolls back again to top.

### To Reproduce

1. Click any link on the navbar.
2. Press back button on the browser.

### Expected Behavior

Ideally a user would click the back button to move back to the last webpage he visited.

### Screenshot/ Video

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/69980616/213883102-80e0632f-c95d-4a4b-8c0d-f6c7b592523b.gif)

**Comment by Chandraprakash-Darji** [comment]
@Sreejit-Sengupto this is not bug. This is the how browser works.
