### ISSUE TITLE
[feat] Back to top button

### ISSUE THREAD

**Issue by Sreejit-Sengupto** [WeMakeDevs/wemakedevs#360]
### Would you like to have a new feature? Please describe.

A scroll to top button would be nice.

### How would this feature be beneficial for the project

Users can directly move to the top using the button.

**Comment by Chandraprakash-Darji** [comment]
That is great thing to add

**Comment by Chandraprakash-Darji** [comment]
Thanks, @Sreejit-Sengupto for a recommendation.

**Comment by nsundriyal62** [comment]
please assign this issue to me! can i resolve it?

**Comment by Chandraprakash-Darji** [comment]
@nsundriyal62 what package you are going to use?

**Comment by nsundriyal62** [comment]
react

**Comment by Chandraprakash-Darji** [comment]
@nsundriyal62 are you worklng on it?

**Comment by Sreejit-Sengupto** [comment]
I have started working on it today! Actually my exams were going on, therefore I was unable to manage. If nobody is working on this then I can take it up, it's almost done.

**Comment by Sreejit-Sengupto** [comment]
I'm done! If nobody has worked for it, I'm ready to raise a PR.

**Comment by nsundriyal62** [comment]
As I said, I was learning  react to solve  this issue, but now it appears that my mind is slowing as compared to the demand of the bug.

Anyone who has already solved it can raise a PR. I will commit my code for more enhancements after I finish working on it.



From my side, I apologize for taking up so much time, and if this seems urgent, you may unassign me.



@Chandraprakash-Darji thanks sir.

**Comment by Sreejit-Sengupto** [comment]
Ok! Then I am moving forward with it.

**Comment by Chandraprakash-Darji** [comment]
@nsundriyal62 keep learning. Soon you will find other issue to work on. Keep building. 

@Sreejit-Sengupto I assign you.

**Comment by Sreejit-Sengupto** [comment]
Hey I need little help! 
![image](https://user-images.githubusercontent.com/69980616/217058455-0a83d729-340f-4fd8-99bb-b2e7dcd5a82b.png)

How to fix these?

**Comment by Chandraprakash-Darji** [comment]
Sort the imports of the file mentioned in the warning by clicking `Ctrl+Shift+. or Shift+Cmd+.` on the import and select fix it

**Comment by Sreejit-Sengupto** [comment]
Done! Created PR, thankyou so much for your help!
