### ISSUE TITLE
[feat] Main courses page

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#362]
### Would you like to have a new feature? Please describe.

Main courses page
- [ ] Header
- [ ] About
- [ ] Courses grid like in last website
    - [ ] #363
    - [ ] #364
    - [x] #365
- [ ] Courses testimonials
- [ ] Join
- [ ] Courses related FAQ
- [ ] Partner
- [ ] Footer

**Comment by Parvej2001** [comment]
On it with @Chandraprakash-Darji

**Comment by Snach13** [comment]
so u want basically a new or better implementation of these sections !!

**Comment by Chandraprakash-Darji** [comment]
@Snach13 this is issue solved @kunal-kushwaha will close it soon

**Comment by Chandraprakash-Darji** [comment]
Done: https://wemakedevs.org/courses
