### ISSUE TITLE
DSA

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#363]
### Would you like to have a new feature? Please describe.

Main courses page
- [ ] Header
- [ ] About
    - [ ] Embed the announcement video
    - [ ] Add links here to GitHub (notes and assignments) & YouTube playlist
- [ ] Syllabus
- [ ] Courses testimonials
- [ ] Join
- [ ] Course related FAQ
- [ ] Partner
- [ ] Footer

**Comment by Chandraprakash-Darji** [comment]
Solved: https://wemakedevs.org/courses/dsa
