### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#364]
### Would you like to have a new feature? Please describe.

Main courses page
- [ ] Header
- [ ] About
    - [ ] Embed the announcement video
    - [ ] Add links here to GitHub (notes and assignments) & YouTube playlist
- [ ] Syllabus
- [ ] Courses testimonials
- [ ] Join
- [ ] Course related FAQ
- [ ] Partner
- [ ] Footer

**Comment by PrathamAditya** [comment]
Hey! Kunal Should i start working on this or you have some sort of theme of the page

**Comment by Chandraprakash-Darji** [comment]
@PrathamAditya this is also solved
