### ISSUE TITLE
Git/GitHub

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#365]
### Would you like to have a new feature? Please describe.

Main courses page
- [ ] Header
- [ ] About
    - [ ] Embed the video
- [ ] Syllabus
- [ ] Courses testimonials
- [ ] Join
- [ ] Course related FAQ
- [ ] Partner
- [ ] Footer

**Comment by mohd-raza** [comment]
Hey @kunal-kushwaha, can you assign me any one of the tasks which is needed to be done, I want to contribute as much as I can. I would be glad to contribute.

**Comment by Ankur1493** [comment]
working on it

**Comment by PrathamAditya** [comment]
Hey can you explain me in what way i can contribute to this?

**Comment by Chandraprakash-Darji** [comment]
Done: https://wemakedevs.org/courses/git-github
