### ISSUE TITLE
add new company

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#366]
Add company Clicklabs for our students work at 
<img width="1803" alt="Screenshot 2023-01-23 at 4 32 48 pm" src="https://user-images.githubusercontent.com/42698533/214103024-72404cf1-4c74-4097-8a81-9d9b71098ef0.png">

**Comment by Parth123Ahuja** [comment]
Should I add the link of career page to that or just there websites.

**Comment by kirtanchandak** [comment]
Hey, can I work on this issue ?

**Comment by Prateema1** [comment]
> Add company Clicklabs for our students work at <img alt="Screenshot 2023-01-23 at 4 32 48 pm" width="1803" src="https://user-images.githubusercontent.com/42698533/214103024-72404cf1-4c74-4097-8a81-9d9b71098ef0.png">

Hi, Can I work on this enhancement?

**Comment by kirtanchandak** [comment]
### Hey, I have added the clicklabs image, but while commiting I am getting a eslint error- 
 
![click](https://user-images.githubusercontent.com/92196705/214579617-bb28a0e1-16bb-492e-b13c-4c11c231df95.png)
![err](https://user-images.githubusercontent.com/92196705/214579649-950ed9b6-8cbb-41d2-a5c1-3e82ff72533b.png)

**Comment by Prateema1** [comment]
> ### Hey, I have added the clicklabs image, but while commiting I am getting a eslint error-
> ![click](https://user-images.githubusercontent.com/92196705/214579617-bb28a0e1-16bb-492e-b13c-4c11c231df95.png) ![err](https://user-images.githubusercontent.com/92196705/214579649-950ed9b6-8cbb-41d2-a5c1-3e82ff72533b.png)

From the error message, it seems like an extra < token(incomplete HTML tag) might be present in your index.jsx file. Line no: 17. As, I haven't committed to the project yet, I am unaware about the issue.

**Comment by kirtanchandak** [comment]
I think it's not an extra HTML tag, because the website is running fine when I do - npm start

**Comment by kirtanchandak** [comment]
### I think it's not an extra html tag because when I doing "npm start" the website is running fine and giving me a warning - 
![Screenshot 2023-01-25 193131](https://user-images.githubusercontent.com/92196705/214583518-67d1db2d-257f-43f5-95d3-79b6170e6d40.png)

**Comment by Prateema1** [comment]
> ### I think it's not an extra html tag because when I doing "npm start" the website is running fine and giving me a warning -
> ![Screenshot 2023-01-25 193131](https://user-images.githubusercontent.com/92196705/214583518-67d1db2d-257f-43f5-95d3-79b6170e6d40.png)

Hey, Have you fixed the warning? 
In the Work component's index.jsx file, when we import the images, if the imports are not in sorted order, the warning is by eslint package. You can manually place clickLabs import after Cisco image import or run the auto fix script. Can you try once?

**Comment by kirtanchandak** [comment]
tried, not working!

**Comment by Chandraprakash-Darji** [comment]
@kirtanchandak share the code then we can say where is the problem

**Comment by kirtanchandak** [comment]
```
import clsx from 'clsx';

import styles from './index.module.css';

import Adobe from '../../../assets/home/adobe.svg';
import Amazon from '../../../assets/home/amazon.svg';
import Cisco from '../../../assets/home/Cisco.svg';
import Clicklabs from '../../../assets/home/Clicklabs.svg';
import Google from '../../../assets/home/google.svg';
import Microsoft from '../../../assets/home/microsoft.svg';
import Razorpay from '../../../assets/home/razorpay.svg';
import Samsung from '../../../assets/home/Samsung.svg';
import Virtusa from '../../../assets/home/virtusa.svg';

const index = () => {
  return (
    <div>
      <div className={clsx('layout', styles.layout)}>
        <h2 className='h1'>Our students work at</h2>
        <hr className={clsx('styled-hr', styles.headingWorkLine)} />
        <div className={styles.workImg}>
          <img className={styles.workGoogle} src={Google} alt='google' />
          <img className={styles.workAmazon} src={Amazon} alt='amazon' />
          <img className={styles.workMicro} src={Microsoft} alt='microsoft' />
          <img className={styles.workAdobe} src={Adobe} alt='adobe' />
          <img className={styles.Samsung} src={Samsung} alt='samsung' />
          <img className={styles.virtusa} src={Virtusa} alt='virtusa' />
          <img className={styles.Cisco} src={Cisco} alt='Cisco' />
          <img className={styles.Razorpay} src={Razorpay} alt='Razorpay' />
          <img className={styles.Clicklabs} src={Clicklabs} alt='Clicklabs' />
        </div>
      </div>
    </div>
  );
};

export default index;
```

**Comment by melsonic** [comment]
can i work on this ?

**Comment by AnuragThePathak** [comment]
@kirtanchandak are you still working on it?

**Comment by Chandraprakash-Darji** [comment]
@melsonic do you want to do?

**Comment by melsonic** [comment]
Thanks @AnuragThePathak

**Comment by GH-aditya** [comment]
Can i work on this

**Comment by AnuragThePathak** [comment]
@GH-aditya already the PR has been created.
