### ISSUE TITLE
one small correction on home page

### ISSUE THREAD

**Issue by kaustubhsaraf** [WeMakeDevs/wemakedevs#367]
### Describe the bug

Plz give space between {and ,n tag} in the how to participate section.

### Screenshot/ Video

![Screenshot_20230123_231030](https://user-images.githubusercontent.com/99542142/214110967-d9b899b6-7b1c-4b07-bb11-fdb95b11c45e.png)

**Comment by Parth123Ahuja** [comment]
Please assign me this .

**Comment by Prateema1** [comment]
Hi, I can see the issue thread is still open. This will be my first issue getting hands-on with open-source contributions.  Can you please assign me to the above task?
