### ISSUE TITLE
Clicking the logo doesn't navigate to the top of the page

### ISSUE THREAD

**Issue by suryanshsoni120** [WeMakeDevs/wemakedevs#373]
### Describe the bug

Selecting a particular tab takes us to that section, like clicking on courses takes us to the courses section on the site. But nothing happens if the user clicks the 'we make devs' logo. Instead, the user should be navigated to the top of the page.

### To Reproduce

1. Click any link on the navbar.
2. Click the 'we make devs' logo button.

### Expected Behavior

The user should be taken to the top of the webpage.

**Comment by arjavsethi** [comment]
I would like to work on this issue

**Comment by harmanbatheja15** [comment]
If this issue is still open, please assign it to me.

**Comment by AnuragThePathak** [comment]
@harmanbatheja15 a PR is already created actually but due to unknown reasons the author is no longer responding. Maybe we should give a little more time. If he still doesn't respond you can have the chance, just remind us in 3-4 days.

**Comment by lingaiahdanda** [comment]
@AnuragThePathak , I can work on this if this is still open.

**Comment by AnuragThePathak** [comment]
@harmanbatheja15 also showed interest in working on it.

**Comment by lingaiahdanda** [comment]
@AnuragThePathak . please assign me when no one is ready to take. thanks

**Comment by harmanbatheja15** [comment]
Solved the issue and opened the pull request. Please review it.

**Comment by AnuragThePathak** [comment]
@lingaiahdanda since we have already got 2 PRs, I would not suggest you to create a new PR. I am hopeful that @harmanbatheja15 will cooperate with the reviewers for fast resolution of the issue.
