### ISSUE TITLE
[bug] Redirect Wrong page

### ISSUE THREAD

**Issue by Bawanthathilan** [WeMakeDevs/wemakedevs#376]
### Describe the bug

On the home page event button currently redirect to we make devs GitHub page. it should be redirected to https://wemakedevs.org/events page

**Comment by Bawanthathilan** [comment]
I can work this issue

**Comment by Chandraprakash-Darji** [comment]
@Bawanthathilan Thanks for the issue

**Comment by Chandraprakash-Darji** [comment]
@Bawanthathilan you should consider this changes too
- [ ]  Courses btn go to courses page and events to event page in home page in new tab
![image](https://user-images.githubusercontent.com/93640141/215712535-96ce6fe3-b078-4a1e-a664-abf58a8e5677.png)
- [ ]  The ongoing event should open in new tab
![image](https://user-images.githubusercontent.com/93640141/215712611-be8bf29a-3c62-40e5-86ad-6283986e0840.png)

**Comment by Parth123Ahuja** [comment]
While hovering over the event button the cursor desing is not changing , while it change on other buttons .
Please check the code

<img width="1067" alt="Screenshot 2023-01-31 at 3 38 44 PM" src="https://user-images.githubusercontent.com/91719157/215731163-c1fe33b1-05c2-4a6b-8d02-d3c2d9a8aae9.png">

**Comment by melsonic** [comment]
Can I work on this issue?
