### ISSUE TITLE
[bug] Icons don't describe there work om stats section of event page

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [WeMakeDevs/wemakedevs#379]
### Describe the bug

![image](https://user-images.githubusercontent.com/93640141/215718948-21111269-f2ad-4c33-aad5-60382d16e5fe.png)

This icons should be updated

### To Reproduce

1. Visit: https://wemakedevs.org/events
2. Scroll to the section: `Stats about prizes`

### Expected Behavior

For money, We can use `MdOutlineAttachMoney`
For country we can use flag `FaFontAwesomeFlag`
For Winnners `BsFillTrophyFill`
For events we can use `VscSymbolEvent`

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this issue?
