### ISSUE TITLE
[bug] Event Repo button should not be there in Events page

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [WeMakeDevs/wemakedevs#380]
### Describe the bug

![image](https://user-images.githubusercontent.com/93640141/215721710-9ed9f397-69d7-4416-a025-3351910bcce6.png)

The event reop button should be removed because it archived.

### To Reproduce

1. Visit https://wemakedevs.org/events
2. Scroll to the about section

### Expected Behavior

It should not be there

**Comment by shubhamku044** [comment]
Hey, Assign it to me. I will raise a PR now.

**Comment by shubhamku044** [comment]
![image](https://user-images.githubusercontent.com/77788249/215723944-9415bcba-5471-4cef-9b2d-901f05d0ae0b.png)
It's done
