### ISSUE TITLE
[bug] Cancel icon should be in a row

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#384]
### Describe the bug

When the screen is at `768px` the check-out upcoming banners wrap their text that leads to the `cancel icon` changing its row.

### To Reproduce

1. Go to https://wemakedevs.org/
2. Right-click and `inspect` the website.
3. Set the screen size to `768px`.
4. See the error in the checkout upcoming events banner.

### Expected Behavior

The `cancel` icon in the checkout upcoming banner should be in a row at screen size `768px`

![check](https://user-images.githubusercontent.com/97666287/215775448-0103cb20-f0fb-4b5f-a216-b50b167ec179.png)

### Screenshot/ Video

![events](https://user-images.githubusercontent.com/97666287/215774950-edf64397-db49-4955-a948-be25ef1cbf36.png)

**Comment by Chandraprakash-Darji** [comment]
@Rishav1707 Thanks for raising the issue
