### ISSUE TITLE
[bug] Cursor pointer should be changed

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#385]
### Describe the bug

Two different `cursor` pointers are in the same `organisations` and `community` columns in the footer sections.

### To Reproduce

1. Go to https://wemakedevs.org/
2. Scroll down to the `footer`.
3. Point the `cursor` on any one of the options.
4. See the error.

### Expected Behavior

The `cursor` pointer should be the same in all the columns in the footers section.

### Screenshot/ Video

The `cursor` pointer should be this:
![WhatsApp Image 2023-01-31 at 6 45 34 PM](https://user-images.githubusercontent.com/97666287/215777122-6f8778c4-56b9-4862-b940-2c53b577ea79.jpeg)

Instead of this:
![WhatsApp Image 2023-01-31 at 6 45 34 PM (1)](https://user-images.githubusercontent.com/97666287/215777211-aacfed2c-870c-4dd0-8957-e51adc3c8ff5.jpeg)

**Comment by Chandraprakash-Darji** [comment]
@Rishav1707 The cursor which is like arrow indicates that it is opening in new tab and cursor which is pointer open in same page

**Comment by Chandraprakash-Darji** [comment]
It is not a bug

**Comment by Rishav1707** [comment]
Ok @Chandraprakash-Darji
