### ISSUE TITLE
[bug] Twitter post height unequal

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#396]
### Describe the bug

The `carousel` of the Twitter post is not equal in `height` below the events section.

### To Reproduce

1. Go to https://wemakedevs.org/
2. Scroll down to the Events section.
3. See the error.

### Expected Behavior

All the carousels should be in `equal height` below the Events section.

### Screenshot/ Video

![Screenshot (19)](https://user-images.githubusercontent.com/97666287/216324452-bb94a806-598d-4818-b310-af19fe47f9e2.png)

**Comment by Chandraprakash-Darji** [comment]
@Rishav1707 height depends on what the content of tweet we can't change it

**Comment by Rishav1707** [comment]
> @Rishav1707 height depends on what the content of tweet we can't change it

Ohh ok @Chandraprakash-Darji
