### ISSUE TITLE
[bug] Set body font-weight to regular

### ISSUE THREAD

**Issue by vikasganiga05** [WeMakeDevs/wemakedevs#400]
### Describe the bug

The current font-weight for the body text is too bold, making it difficult to read for some users. It would be great if we set the body text font-weight to regular to improve readability.

### To Reproduce

1. Open the website
1. Observe the font-weight of the body text

### Expected Behavior

One possible solution is to add a CSS rule that sets the font-weight property for the body text to "400" (regular).
Or 
Just remove the font-weight property from the body selector.

### Screenshot/ Video

**Here is the screenshots of before and after adding regular font-weight to the body of the website.**
| Before | After |
| --- | --- |
| ![before image](https://user-images.githubusercontent.com/74750414/216510933-d01b6611-f124-4554-ba7c-f93e11447f94.png) | ![after image](https://user-images.githubusercontent.com/74750414/216510664-470e16f4-f5aa-4a22-9ca8-04efb1cb0ab3.png) |

### Additional context

This change is necessary to improve the readability of the text and ensure a consistent style across all pages.

**Comment by hirentimbadiya** [comment]
can i work on this bug ? assign me this issue please!!

**Comment by Chandraprakash-Darji** [comment]
@hirentimbadiya I will recommend not to work on until issue is certified and assigned to you.

**Comment by vikasganiga05** [comment]
> @vikasganiga05 @hirentimbadiya I guess it is properly readable I have tested for the people also

Okay, Thanks for informing :slightly_smiling_face:
