### ISSUE TITLE
[docs] Enhancing the look of the README.md file

### ISSUE THREAD

**Issue by the-amazing-atharva** [WeMakeDevs/wemakedevs#408]
### Category of documentation update

Restructuring the layout of the README

### Describe the change you think might work

+ Changing the positions of certain elements
+ Changing the orientation and look of certain texts to look more visually appealing
+ TBC

**Comment by ArslanYM** [comment]
Can I work on this issue ? 
I think changing the position of the wemakedevs logo and then hands on keyboard image will look better. 
The wemakedevslogo on top on the other one will enhance the look.

**Comment by the-amazing-atharva** [comment]
Hey there!

I am also a contributor and not a repository author with access. There seems to be a clash !

**Comment by AnuragThePathak** [comment]
What kind of restructure do you have in mind, be more specific or provide visual sample etc

**Comment by SaadAnsari17** [comment]
This section can be improved there should be either text or image
