### ISSUE TITLE
[feat] Add the Gitpod ready-to-code system

### ISSUE THREAD

**Issue by Panquesito7** [WeMakeDevs/wemakedevs#409]
### Would you like to have a new feature? Please describe.

With [Gitpod](https://www.gitpod.io), anyone can easily build the website and make contributions in one single click.
This means you don't have to install anything on your PC: just click on the Gitpod button, and everything should be built (needs configuration).

### How would this feature be beneficial for the project

This would make it easier for contributors to check their changes (if they made any website changes) as well as deploy the website without installing any extra tools/frameworks.

### Additional context

If you like this idea, I'd like to work on this. 🙂

**Comment by AnuragThePathak** [comment]
@Panquesito7 technically we don't feel it is required as we've got GitHub Codespaces.
