### ISSUE TITLE
[docs] Update the CoC given mail

### ISSUE THREAD

**Issue by Panquesito7** [WeMakeDevs/wemakedevs#410]
### Category of documentation update

In the [Code of Conduct](https://github.com/WeMakeDevs/wemakedevs/blob/main/CODE_OF_CONDUCT.md) file, the provided email is outdated and shouldn't be used anymore. This should be updated as soon as possible.

_Steps to contribute_

1. [Fork](https://github.com/WeMakeDevs/wemakedevs/fork) the repository.
2. Create a new branch named `fix_email`.
3. Open the `CODE_OF_CONDUCT.md` file, located in the root directory.
4. In the [Enforcement](https://github.com/WeMakeDevs/wemakedevs/blob/main/CODE_OF_CONDUCT.md#enforcement) section, change the given mail. `kunal@commclassroom.org` -> `kunal@wemakedevs.org`
5. Commit and push your changes.
6. Create a [pull request](https://github.com/WeMakeDevs/wemakedevs) to compare the changes.
7. You're done now! 🎉 You just have to wait until the maintainers review your PR.

If you need any help with this, let us know! 🙂
**Please leave this issue open to first-time contributors and beginners.**

**Comment by himanshu1221** [comment]
can i work on this issue ?

**Comment by methlox** [comment]
@Panquesito7 I created a pull request for the same. Please verify!

**Comment by ArslanYM** [comment]
Can I work on this issue please?

**Comment by PrathamAditya** [comment]
hey! everybody is the issue is open or some is working on this?

**Comment by gaurab-khanal** [comment]
Hi I am new to opensource and development. Can I contribute to this? Please assign me this issue.

**Comment by Panquesito7** [comment]
This has been already made in #411.
