### ISSUE TITLE
[docs] Readme Update

### ISSUE THREAD

**Issue by himanshu1221** [WeMakeDevs/wemakedevs#412]
### Category of documentation update

<h1>Adding contributing guidelines to readme file</h1>

### Describe the change you think might work

<h3>Contributing Guidelines file is already present in the repository we can add that file in readme.md file so it would be more helpful </h3>

![Screenshot from 2023-02-09 15-48-38](https://user-images.githubusercontent.com/32031706/217784805-2cc1cc29-3b40-45af-8ceb-d67e4cb2ea67.png)

**Comment by vikaskumar2703** [comment]
i can bring the required please assign me this issue if no one workin on it

**Comment by rohitguptaa22** [comment]
hi team, added the PR for solving the issue. Kindly check and merge the PR.
@himanshu1221

**Comment by vikaskumar2703** [comment]
hey @himanshu1221 were u assigned this issue?

**Comment by himanshu1221** [comment]
> hey @himanshu1221 were u assigned this issue?

No i wasn't assigned

**Comment by vikaskumar2703** [comment]
hey @rohitguptaa22  were u assigned this issue?

**Comment by rohitguptaa22** [comment]
No bro

**Comment by Snach13** [comment]
can I created PR for it

**Comment by AnuragThePathak** [comment]
@himanshu1221 is this issue about adding the content from contributing.md to readme.md

**Comment by himanshu1221** [comment]
> @himanshu1221 is this issue about adding the content from contributing.md to readme.md

Yes 
As the file is already present we should add that in the Readme file as it would be more easier to understand

**Comment by rupeshexe** [comment]
> @himanshu1221 is this issue about adding the content from contributing.md to readme.md

Hey, I already have a PR open on this #422

**Comment by himanshu1221** [comment]
> > @himanshu1221 is this issue about adding the content from contributing.md to readme.md
> 
> Hey, I already have a PR open on this #422

Were you assigned for this issue ?

**Comment by AnuragThePathak** [comment]
I'm closing this issue as it is not realistic to repeat things and it'll also defy the purpose of having a contributing.md
