### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Snach13** [WeMakeDevs/wemakedevs#417]
### Describe the bug

In the about us section, there are 3 buttons or links one is discord another telegram, and last newsletter whenever a user hover over them color is changed and customize cursor appeared but on the newsletter button hand pointer is appearing 
![bug](https://user-images.githubusercontent.com/97365258/218166174-34d7fc01-5090-43fe-bddd-f32fc4c9b167.png)

### Expected Behavior

so the same customize cursor needs to appear on newsletter button alsothe 

### Screenshot/ Video

![bug](https://user-images.githubusercontent.com/97365258/218166526-322ffd4d-329a-48c4-ba65-585628755f65.png)

**Comment by Chandraprakash-Darji** [comment]
@Snach13 Pointer because when you click it will not navigate you to a new tab. other btn will navigate you to the new page.

**Comment by Prakashcreator** [comment]
@Chandraprakash-Darji I saw the source code for above issue. If link start with # Cursor will be normal.

**Comment by Chandraprakash-Darji** [comment]
This is not the issue it is intended feature
