### ISSUE TITLE
[bug] Telegram link was invalid.

### ISSUE THREAD

**Issue by Prakashcreator** [WeMakeDevs/wemakedevs#418]
### Describe the bug

Telegram link was Invalid for Desktop.

### To Reproduce

1. Go to Join us section.
2. Click on Telegram Link.
3. Check Telegram link was invalid.

### Expected Behavior

Telegram link need to navigate to it respective Telegram channel.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/95578587/218178692-9d834eff-eda1-48da-8eb2-e10603a251e3.png)

### Additional context

Add the respective telegram link for Desktop.

**Comment by ShuvamChatterjee28** [comment]
Hello, can I work in this issue?

**Comment by ArslanYM** [comment]
Hey, Can I work on this issue as it would be my first open-source contribution? Please

**Comment by ArslanYM** [comment]
It's working already! @Prakashcreator 
![Screenshot 2023-02-11 104853](https://user-images.githubusercontent.com/104521101/218241690-4fa5399f-9857-4a62-a057-b98a90142e2c.png)

**Comment by Chandraprakash-Darji** [comment]
It is working
