### ISSUE TITLE
[docs] Making the logos of used technologies like HTML5 ,CSS , NodeJs etc clickable to their respective documentation. 

### ISSUE THREAD

**Issue by ArslanYM** [WeMakeDevs/wemakedevs#419]
### Category of documentation update

This would make the Readme file more enhanced and useful for beginners.

### Describe the change you think might work

Add the links to the respective logos and make them linked to the actual documentation.

**Comment by gaurab-khanal** [comment]
@ArslanYM Should I need to add respective link to the respective logos to make them navigate to their sites?
![image](https://user-images.githubusercontent.com/40165867/218244674-022464b1-085d-4f72-8ed1-5dcb251b345b.png)
If it is so then I have figured-out the solution to add link to these logos and make them navigate to their respective sites.
Please, assign me this issue. I am new to opensource and want to grow.

**Comment by ArslanYM** [comment]
> @ArslanYM Should I need to add respective link to the respective logos to make them navigate to their sites? ![image](https://user-images.githubusercontent.com/40165867/218244775-1971629a-6c19-47a7-887e-a91c00ca8776.png)
> 
> If it is so then I have figured-out the solution to add link to these logos and make them navigate to their respective sites. Please, assign me this issue. I am new to opensource and want to grow.

**Comment by ArslanYM** [comment]
@gaurab-khanal im not a member of the team , so i can't assign you for the task. I also want to contribute and therefore I'm just raising issues which would benefit the project. A member of the main team can only assign you for this task.

**Comment by AnuragThePathak** [comment]
@gaurab-khanal you may start working without getting assigned too in case of these small changes.

**Comment by ArslanYM** [comment]
Working on it.

**Comment by gaurab-khanal** [comment]
> @gaurab-khanal you may start working without getting assigned too in case of these small changes. It will barely take 5 minutes to perform the required changes and create a PR.

Thank you for assigning me. Will fix soon.

**Comment by ArslanYM** [comment]
> @gaurab-khanal you may start working without getting assigned too in case of these small changes. It will barely take 5 minutes to perform the required changes and create a PR.

I wanted to work on it :(

**Comment by ArslanYM** [comment]
@AnuragThePathak  please merge the changes that close this issue. It would be my first open source contribution
