### ISSUE TITLE
[bug] Event section slider is not working

### ISSUE THREAD

**Issue by rakeshVerse** [WeMakeDevs/wemakedevs#430]
### Describe the bug

Slider on event section is not moving but the three dots are changing colors. 

![Screenshot from 2023-02-13 18-13-11](https://user-images.githubusercontent.com/100757764/218460798-1ff379fa-c45d-4b09-bcf7-b94fb3481fd4.png)

### To Reproduce

1. Go to https://wemakedevs.org/
2. Click on 'Events' on navigation bar
3. See error

### Expected Behavior

- Slider should auto slide
- Slider should slide when the dots are clicked

**Comment by melsonic** [comment]
The slider is for the tweets, which has not been loaded on your screen. 
see below...
<br>
![image](https://user-images.githubusercontent.com/88551650/218464449-75fe7981-1e80-4181-abb2-01d1ec0a212e.png)

**Comment by rakeshVerse** [comment]
No, I'm taking about **Event** section on Home Page. I've tested it on Mozilla Firefox and Chromium Browser.

Please follow the steps I've mentioned in the issue ticket or visit: https://wemakedevs.org/#events **to reproduce** the bug.

**Comment by rakeshVerse** [comment]
@AnuragThePathak Understood, but I kept the site opened for very long and waited for tweets to load, but they didn't on either of the browser. 
If the tweets often takes a considerable amount of time to load, my suggestion would be show the slider dots only after receiving tweets. Because it doesn't look good when the dots are changing colors but there's no content to slide.

**Comment by AnuragThePathak** [comment]
Makes sense but I'm not sure how important that task is as compared to others.

**Comment by rakeshVerse** [comment]
@AnuragThePathak Sure, that's up to you. I just found the bug so I reported it.
