### ISSUE TITLE
[bug]No slider or button present to slide testimonial in small screen

### ISSUE THREAD

**Issue by anikdhabal** [WeMakeDevs/wemakedevs#436]
### Describe the bug

No slider or button present to slide testimonial in small screen

### To Reproduce

1.Oprn WeMakeDev
2.Restore Down your screen
3.Try to slide testimonial

### Expected Behavior

A slider should be present to slide.

### Screenshot/ Video

<img width="459" alt="Screenshot 2023-02-15 235554" src="https://user-images.githubusercontent.com/81948346/219118996-f8a0f752-77d1-451c-bbd3-c0322dc2b253.png">

**Comment by anikdhabal** [comment]
can I work on this ?

**Comment by Chandraprakash-Darji** [comment]
You can directly swipe and see all the testimonial

**Comment by Chandraprakash-Darji** [comment]
Have you tried that

**Comment by anikdhabal** [comment]
@Chandraprakash-Darji how?

**Comment by yashnigamp** [comment]
Yes by sliding it is working on small screens verified.
