### ISSUE TITLE
[bug] Responsive for Mobile Screen.

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#438]
### Describe the bug

![flexwrap](https://user-images.githubusercontent.com/97666287/219342373-fe3973ff-8386-41c7-ad9b-e42f28815261.png)

### To Reproduce

1. Go to https://wemakedevs.org/
2. `Right` click and `inspect` the website.
3. Set the screen size to `375px`.
4. Scroll down to `Partner with us` section.
5. See error.

### Expected Behavior

![flex](https://user-images.githubusercontent.com/97666287/219343320-d8cd13c9-0710-4e04-bc31-5c0e9fe98f79.png)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by hparashar27** [comment]
@Chandraprakash-Darji can i work on this ?

**Comment by gaurab-khanal** [comment]
Hey @Chandraprakash-Darji  Please assign me this issue. I am new to opensource.

**Comment by Chandraprakash-Darji** [comment]
@gaurab-khanal you are late you may find another issue. @hparashar27 I assign you.

**Comment by gaurab-khanal** [comment]
@hparashar27   are you still working on this?

**Comment by Rajeevjewar** [comment]
I am new in open source so I want to work on it so please assign this issue to me.

**Comment by Chandraprakash-Darji** [comment]
@Rajeevjewar It is great that you are starting open source but this is issue is already assigned

**Comment by Rajeevjewar** [comment]
Ok no way,
but i will keep contribute to upcoming issues or may be generate new issues.

**Comment by Chandraprakash-Darji** [comment]
@Rajeevjewar All the best

**Comment by himanshuSri24** [comment]
@Chandraprakash-Darji hey! Is this issue still available to be fixed? If yes, I'd love to work on this! Just getting started with open source!

**Comment by Chandraprakash-Darji** [comment]
@himanshuSri24 welcome to open source, @hparashar27 is working on it, you can help him out

**Comment by himanshuSri24** [comment]
Sure shot! @hparashar27 , would you mind if I try working on this bug with you?

**Comment by hparashar27** [comment]
@hparashar27 ya sure , you can start working on this bug 👍

**Comment by himanshuSri24** [comment]
@Chandraprakash-Darji I've created a pull request. Kindly verify it and merge it. Thanks!
