### ISSUE TITLE
[bug] Upcoming Events Banner not responsive for mobile screen.

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#439]
### Describe the bug

![resp](https://user-images.githubusercontent.com/97666287/219344065-55fa15b2-2e62-44fd-acde-dd93c9ddcaaf.png)

### To Reproduce

1. Go to https://wemakedevs.org/
2. `Right` click and `inspect` the website.
3. Set the screen size to `375px`.
4. See error.

### Expected Behavior

![responsive](https://user-images.githubusercontent.com/97666287/219344393-6eb5b525-5c18-4a97-b6f2-918b070d747e.png)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by Chandraprakash-Darji** [comment]
@Rishav1707 thanks for the issue. I am assigning you. Just add the css `shrink: 0` to the icon becuse it is shrinking

**Comment by Rishav1707** [comment]
> @Rishav1707 thanks for the issue. I am assigning you. Just add the css `shrink: 0` to the icon becuse it is shrinking

In which icon?? Events?

**Comment by Rishav1707** [comment]
> @Rishav1707 thanks for the issue. I am assigning you. Just add the css `shrink: 0` to the icon becuse it is shrinking

Thank you😊 @Chandraprakash-Darji for guiding me.
