### ISSUE TITLE
[bug]Hover effect on Newsletter button in About Us section does not work

### ISSUE THREAD

**Issue by MaruthiKo** [WeMakeDevs/wemakedevs#450]
### Describe the bug

The hover effect which changes the pointer to an arrow does not work for the Newsletter button in the about us section

### To Reproduce

1. Go to https://wemakedevs.org/
2. Hover on 'Newsletter' in the about us section
3. See the normal pointer

### Expected Behavior

The normal pointer should be an arrow that is similar to other links on the page

### Screenshot/ Video

https://user-images.githubusercontent.com/63769209/220028362-397c9003-31fc-4587-b3a6-c467c073f8fa.mp4

**Comment by MaruthiKo** [comment]
I would like to work on this issue

**Comment by gaurab-khanal** [comment]
Can I work on this issue? I am new to opensource and want to learn and grow with community.

**Comment by SuyashPatil-29** [comment]
I would really like to work on this issue, I am new to opensource. @MaruthiKo

**Comment by MaruthiKo** [comment]
Okay go ahead 
If you have any doubts let me know

**Comment by KartikMakhloga** [comment]
I would like to work on this can you please assign me the issue?

**Comment by Chandraprakash-Darji** [comment]
@MaruthiKo you are first so i am to assigning you. 

Actually, this is not a bug, It is a feature that like shows the arrow then it will open in a new tab, and if it shows the pointer then on the same website. 

But people are thinking this is a bug. So I guess let's remove this feature

there is class name `new-tab` in root.css just removing that it will be ok
