### ISSUE TITLE
Fotter Padding

### ISSUE THREAD

**Issue by JasonDsouza212** [WeMakeDevs/wemakedevs#452]
### Describe the bug

There seems to be more bottom padding in the footer in both desktop and mobile views.
## With notification

![Screenshot from 2023-02-20 14-23-42](https://user-images.githubusercontent.com/74404894/220073485-8b461aea-396a-4763-af91-ee02a98cb3ef.png)

## Without notification

![Screenshot from 2023-02-20 14-23-51](https://user-images.githubusercontent.com/74404894/220073478-73aa6b80-ce7d-4c72-a6af-5663dcdfbe30.png)

I think this issue is happening because of the notification banner at the bottom.

### Expected Behavior

- We can have bottom padding for footer if the banner is present.
- If the banner isn't present, it's better to reduce the bottom padding.

**Comment by Chandraprakash-Darji** [comment]
@JasonDsouza212 Thanks for the issue.

**Comment by MaruthiKo** [comment]
I would like to work on this issue

**Comment by Chandraprakash-Darji** [comment]
@MaruthiKo How would you implement this?

**Comment by MaruthiKo** [comment]
Decrease the height or padding/margin if applied

**Comment by JasonDsouza212** [comment]
I can do that by decreasing  padding-block-end: 6.5rem; in mobile view and also in desktop mode

**Comment by Chandraprakash-Darji** [comment]
Then it might hide the bottom footer text if banner is showing

**Comment by JasonDsouza212** [comment]
yup but increasing slightly wont conver it because I tried it
