### ISSUE TITLE
[bug]: Partner does not align with the rest items on the Navbar

### ISSUE THREAD

**Issue by dev-phantom** [WeMakeDevs/wemakedevs#454]
### Describe the bug

on the landing page in the navbar the partner does not align with the rest items on the Navbar including the icon

### To Reproduce

1. go to [https://wemakedevs.org/](url)
2. check the navbar 
3. see error

### Expected Behavior

the nav items ought to align together

### Screenshot/ Video

![Screenshot from 2023-02-20 23-37-53](https://user-images.githubusercontent.com/72051159/220208842-f554d8fa-759d-4af8-939f-4cb19872df5d.png)

**Comment by dev-phantom** [comment]
i could fix this if i get assigned

**Comment by dev-phantom** [comment]
just realized this issue also exist on other pages

**Comment by Chandraprakash-Darji** [comment]
@dev-phantom thanks for issue. it is happened due to the recent merge. it is fixed now
