### ISSUE TITLE
[bug]: all arrow icons does not align center

### ISSUE THREAD

**Issue by dev-phantom** [WeMakeDevs/wemakedevs#455]
### Describe the bug

the right arrow icons does not align center in the landing page 
they are aligned to the top of the text

### To Reproduce

1. go to [https://wemakedevs.org/](url)
2. see error

### Expected Behavior

the icons ought to be aligned center with the text

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/72051159/220209425-d4f3bc8e-7887-47ff-a04b-09ff2c695bf6.png)

**Comment by Chandraprakash-Darji** [comment]
Fixed

**Comment by Chandraprakash-Darji** [comment]
This is just fixed
