### ISSUE TITLE
[feat]: add link to the upcoming event banner

### ISSUE THREAD

**Issue by dev-phantom** [WeMakeDevs/wemakedevs#456]
### Would you like to have a new feature? Please describe.

in the footer banner whenever i try to click the upcoming events it ought to direct me to [https://wemakedevs.org/#events](url)
so i can check for upcoming events but it doesn't

### How would this feature be beneficial for the project

users can easily be directed to the event page by clicking on the link in the footer

**Comment by Chandraprakash-Darji** [comment]
@dev-phantom it is redirecting to the /events not to /#events

**Comment by dev-phantom** [comment]
just realized this issue has been fixed
