### ISSUE TITLE
[bug]: Contents in Join Us section is not aligned well.

### ISSUE THREAD

**Issue by parth-ranalkar** [WeMakeDevs/wemakedevs#457]
### Describe the bug

Telegram section taking more space than discord section. 
Both section should take equal space 

### To Reproduce

1. Go to [WeMakeDevs](https://wemakedevs.org/#join)
2. See error

### Expected Behavior

Both section should aligned well.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/73604763/220244714-434719c0-ff21-4dae-b545-285b426e0a52.png)

**Comment by Chandraprakash-Darji** [comment]
@parth-ranalkar it is happening due to the dark mode extension. Try to open in incognito

**Comment by Chandraprakash-Darji** [comment]
i got it due to the recent merege it is happening

**Comment by Chandraprakash-Darji** [comment]
Fixed
