### ISSUE TITLE
[bug] Testimonials Loading slowly

### ISSUE THREAD

**Issue by JasonDsouza212** [WeMakeDevs/wemakedevs#465]
### Describe the bug

When navigating to the courses page from the main page, the Testimonials section appears to load too slowly on both desktop and mobile devices

### To Reproduce

Go to https://wemakedevs.org/
click on courses
scroll down to Testimonials
see the error

### Expected Behavior

- The testimonials and other content should load simultaneously
- Otherwise, the section may appear empty and look odd to viewers

### Screenshot/ Video

[Screencast from 25-02-23 01:10:15 PM IST.webm](https://user-images.githubusercontent.com/74404894/221345455-9adcc954-efc4-427c-a69b-ce3162c21018.webm)

**Comment by harmanbatheja15** [comment]
Everything is working fine for me.

**Comment by JasonDsouza212** [comment]
Try going to that section a little faster you can find that

**Comment by Chandraprakash-Darji** [comment]
#435 is this issue contributer is adding a loader to it when the tweets are loaded

**Comment by JasonDsouza212** [comment]
- No, I haven't done anything. I was just testing the website when I found this issue.
- I don't know what is causing this. I can try to check that out
- Can you check if you are facing the same issue on your system?

**Comment by Chandraprakash-Darji** [comment]
@JasonDsouza212 it is not an issue, actully it takes time to fetch the tweet from twitter, so this is the reason

**Comment by JasonDsouza212** [comment]
Wouldn't it be good if all the scripts loaded first before the web page loaded?

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji close this issue as #435 is in progress to fix it?
