### ISSUE TITLE
[other] Reduce bottom padding in Subscribe to Our Newsletter

### ISSUE THREAD

**Issue by JasonDsouza212** [WeMakeDevs/wemakedevs#466]
### What would you like to share?

- It would be beneficial to reduce the bottom padding after the **Subscribe to Our Newsletter** section because there is a large gap between the subscribe button in that section and the **FAQs section**
- Currently, the gap between the two sections is quite large, which may make the website layout appear disjointed to users

![Screenshot from 2023-02-25 12-12-17](https://user-images.githubusercontent.com/74404894/221345778-5d8b7bd1-2438-44f0-8a3d-9045bc8839d0.png)

**Comment by JasonDsouza212** [comment]
Can this Issue be assigned to me

**Comment by msaikat022** [comment]
Hello, are you working on this issue ?

**Comment by JasonDsouza212** [comment]
No

**Comment by JasonDsouza212** [comment]
You can start working on that once the admin assigns you the issue

**Comment by AnuragThePathak** [comment]
@msaikat022 you may start working if you are confident to be able to fix it.

**Comment by himanshuSri24** [comment]
hey @AnuragThePathak , may I work on it as well please?

**Comment by msaikat022** [comment]
@AnuragThePathak Ok i will be doing it.Thank you very much for assigning me this work.

**Comment by msaikat022** [comment]
@AnuragThePathak Hello Anurag . I have made the necessary changes for the following issue. You check regarding the same.

**Comment by msaikat022** [comment]
@AnuragThePathak Hey anurag i have fixed the issue . Please review it let me know what do think. 
#469

**Comment by msaikat022** [comment]
@AnuragThePathak Hey anurag can you please check my pull request . The below one is mine which was assigned to me.
