### ISSUE TITLE
ScrollToTop and Event Close Element Clash [bug]

### ISSUE THREAD

**Issue by Nishaaaanth** [WeMakeDevs/wemakedevs#468]
### Describe the bug

The "Scroll to Top" Icon is placed on top of the "Close" icon on the "Events" banner on mobile phones. 

### To Reproduce

1. On Mobile Phone Resolution go to https://wemakedevs.org/
2. Scroll down a bit
3. Now, you would see the Icon overlaying on top of the "X" Icon

### Expected Behavior

1. Slightly adjust the coordinates of "ScrollToTop" Icon to make sure it doesn't come in the way of "Close" icon of the Event banner.

### Screenshot/ Video

Open the Browser:
![WeMakeDevs-ScrollToTop-Bug](https://user-images.githubusercontent.com/83387409/221408077-8574c77c-7e5f-41d2-8cac-713e6797b016.png)

Scroll down a little:
![WeMakeDevs-ScrollToTop-Bug-2](https://user-images.githubusercontent.com/83387409/221408176-2dfb4183-faf0-46cb-b7d4-c744b7ccd2bf.png)

**Comment by himanshuSri24** [comment]
@Nishaaaanth may I work on this bug?

**Comment by Nishaaaanth** [comment]
Hey @himanshuSri24 it was a very minor change so pushed it myself

**Comment by himanshuSri24** [comment]
Alrightyy!
