### ISSUE TITLE
[feat] Webinar page

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#472]
- [ ] Main overall webinar page (wemakedevs.org/webinar)
  - [ ] Upcoming webinars, cards with event details such as:
    - [ ] topic
    - [ ] date
    - [ ] time
    - [ ] link to main page
  - [ ] Previous webinars (link to webinar page)

- [ ] Individual page for every webinar (wemakedevs.org/webinar/individual-webinar-name)
  - [ ] header
  - [ ] webinar topic + poster
  - [ ] what you will learn
  - [ ] date 
  - [ ] time
  - [ ] speakers
  - [ ] registration form embed (like newsletter, Kunal will send this)
  - [ ] join us
  - [ ] FAQ
  - [ ] Partner with us
  - [ ] footer

- [ ] WeMakeDevs home page, add button to webinars in the events card

**Comment by DhruviThakkar210** [comment]
i want to contribute this page . How can i?

**Comment by Chandraprakash-Darji** [comment]
@DhruviThakkar210 I am going to create a branch for it in a while then I will create a issuee for it then you can contribute

**Comment by DhruviThakkar210** [comment]
@Chandraprakash-Darji  okay , will be waiting !

**Comment by Parvej2001** [comment]
@DhruviThakkar210 yes very soon we will be creating issues . Stay tune for contribution

**Comment by khatri7** [comment]
Hey @Parvej2001 I also wish to contribute to this

**Comment by heyrishabh13** [comment]
Hi, can anyone please let me know how I can contribute?

**Comment by Chandraprakash-Darji** [comment]
@khatri7  @Nainish-Rai @heyrishabh13 thanks for showing intrset in the issue. But, actully it is completed by the team. You can also contribute by creating the issue for the `migrating-tailwindcss` branch. You can see the preview of the website here https://wemakedevs.vercel.app/

**Comment by Parvej2001** [comment]
@ShimpiTejas thankyou for showing your interest. it is completed by  the team. You can contribute by creating issue in migrating-tailwindcss branch.
