### ISSUE TITLE
[other] Favicon change

### ISSUE THREAD

**Issue by Sushants-Git** [WeMakeDevs/wemakedevs#479]
### Changing the favicon from the old logo to the new one

**Changing the old favicon**

![image](https://user-images.githubusercontent.com/100516354/223306298-0688d974-1d75-49eb-bb8f-722e16213576.png)

**to the new favicon**

![image](https://user-images.githubusercontent.com/100516354/223309696-26ad2f8d-0ee0-4c29-a19e-c1ff61de4aec.png)

**Comment by Sushants-Git** [comment]
Do let me know if this change is required, i would be really happy to contribute!

**Comment by Saikat-Mandal** [comment]
hey @Sushants-Git you working on this ?

**Comment by Sushants-Git** [comment]
> hey @Sushants-Git you working on this ?

yes!

**Comment by Saikat-Mandal** [comment]
okay

**Comment by AnuragThePathak** [comment]
What is the need of it?
