### ISSUE TITLE
Sub-Footer Section Hovering

### ISSUE THREAD

**Issue by PrakharSinha-09** [WeMakeDevs/wemakedevs#484]
### Would you like to have a new feature? Please describe.

I Feel it would really look amazing in the perspective OF User Interface when people will come onto the Sub-Footer section which is containing Organisation, Community, Socials & Contact , to each of the options available under them, if we make hoverable edits like color changes to   #5942e9 and text written gets little scaled up...I've tried out the feature and looks really cool!

Same thing I'm thinking for Social Buttons too!
Will be grateful, if I Can contribute too!
Please Assign!

### How would this feature be beneficial for the project

https://user-images.githubusercontent.com/68687087/224511389-335601f2-dacb-40e7-b810-1f6d883040b1.mp4

See, How Cool it is resembling!

**Comment by Saikat-Mandal** [comment]
@PrakharSinha-09 yeh it really does look nice !

**Comment by Varunvaru524** [comment]
I think it will be better to have the same hover animation in the navbar to the footer as well, because the style of the project will stay consistent throughout.

https://user-images.githubusercontent.com/101904494/224563508-a2fe1202-74c2-406f-8183-ca37cc39901c.mp4

**Comment by PrakharSinha-09** [comment]
No, What I Think, is that the underline coming up while hovering on the navbar should be limited to the navbar only as that is something which is making it distinguishable from other sections therefore, I think what I have suggested before looks pretty cool!

**Comment by PrakharSinha-09** [comment]
Hey! There No Response Till.

**Comment by PrakharSinha-09** [comment]
Hey Anurag, I've opened the issue, and was waiting for so long if i get assigned for the task, but somebody came up and opened the pull request and that got  merged too!
Why So ?
I went formally, is that the flaw..?

**Comment by AnuragThePathak** [comment]
@PrakharSinha-09 you should have directly started working and created a PR within a few hours before someone creates their own PR before you.
