### ISSUE TITLE
[bug]Getting this alert when opening the website 

### ISSUE THREAD

**Issue by ArslanYM** [WeMakeDevs/wemakedevs#486]
### Describe the bug

Getting an alert when opening the wemake  devs website . 

### Screenshot/ Video

![wemakedevs](https://user-images.githubusercontent.com/104521101/224780903-75b5805d-2d5c-4278-9c86-3fefb9b7c89b.png)

**Comment by ArslanYM** [comment]
info : the alert goes after clicking on it multiple times

**Comment by Varunvaru524** [comment]
Yeah me too

**Comment by Saikat-Mandal** [comment]
@ArslanYM are you working on this issue?

**Comment by ArslanYM** [comment]
Haven't been assigned yet.

**Comment by ArslanYM** [comment]
@Chandraprakash-Darji can we make it that if this happens console.log the error instead of alerting it ? If yes can i work on this issue?

**Comment by Chandraprakash-Darji** [comment]
in the tailwindcss brach it is already fixed and it will be merged with some days

**Comment by ArslanYM** [comment]
Great , ill close the issue then.
