### ISSUE TITLE
[BUG] Inconsistency in line-height of several sections 

### ISSUE THREAD

**Issue by inclinedadarsh** [WeMakeDevs/wemakedevs#49]
![image](https://user-images.githubusercontent.com/84132532/196739922-cdba2e08-9681-4b02-8705-d9c5367c9505.png)

There is inconsistency in the line height in the title of the sections and also in the paragraphs in the website.

**Comment by inclinedadarsh** [comment]
I can work on this one, please assign it to me.

**Comment by AnuragThePathak** [comment]
You're in the team already, maybe you can work, but consult with the dev team once.
