### ISSUE TITLE
[bug] Community Testimonials not loading in the /events page.

### ISSUE THREAD

**Issue by ArslanYM** [WeMakeDevs/wemakedevs#492]
### Describe the bug

There is some issue with the community testimonials section in the events page 
stuck on loadig: 

### Expected Behavior

Load faster 

### Screenshot/ Video

![we make devs](https://user-images.githubusercontent.com/104521101/226092212-a630d1c3-5ed2-4057-8202-40155873c333.png)

**Comment by Chandraprakash-Darji** [comment]
There might be internet issue or the ad blocker you are using
