### ISSUE TITLE
[feat] Feature Request: Enabling Hover Effects on Footer Icons

### ISSUE THREAD

**Issue by tejash023** [WeMakeDevs/wemakedevs#496]
### Would you like to have a new feature? Please describe.

As a user of the application, I would like to have a better user experience while navigating the application. Currently, the footer icons do not have any hover effects, making it difficult to distinguish them and their functionality. I suggest enabling hover effects on the footer icons to improve the user experience.

### How would this feature be beneficial for the project

Enabling hover effects on the footer icons will provide the following benefits:

- Improved user experience: Users will be able to easily identify the function of each icon, making it easier to navigate the application.
- Better visual aesthetics: Adding hover effects will enhance the visual appeal of the application, making it more attractive and engaging for users.
- Increased usability: With clear and distinguishable icons, users will be able to use the application more efficiently, 

https://user-images.githubusercontent.com/36923392/226189788-266d5924-23bc-4d35-be6b-cd3cee22ac32.mp4

improving overall usability.

### Additional context

The proposed implementation involves adding CSS styles for hover effects on the footer icons. The implementation should be done in a way that is compatible with different browsers and devices. And the color is inline with the primary color being used currently in the website. Please see the video regarding my implementation.

Attaching the video. Thank you for considering this feature request.

**Comment by Saikat-Mandal** [comment]
Hey can i work on this ?

**Comment by tejash023** [comment]
#497
