### ISSUE TITLE
Build the Readme file

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [WeMakeDevs/wemakedevs#50]
Task is to create readme file with the following
- [x] Title
- [x] About
- [ ] Hyperlinks to the essential docs
    - [ ] License
    - [ ] Code of conduct
    - [ ] Contributing
- [ ] Socials

**Comment by iqrafirdose** [comment]
I would like to contribute to this issue . Can I start working?

**Comment by kaiwalyakoparkar** [comment]
Sure go ahead @iqrafirdose if you have any doubts let us know :)

**Comment by AnuragThePathak** [comment]
@saloni0419 not possible to bring it under Hacktoberfest.

**Comment by tcchawla** [comment]
Can I work on this issue? @kaiwalyakoparkar

**Comment by iqrafirdose** [comment]
Hey, @kaiwalyakoparkar I created a pull request #66 . It would be helpful if you check it once and give feedback.

**Comment by iqrafirdose** [comment]
Hey @kaiwalyakoparkar, can you please explain to me what greeting means failed? Why does it happen?

**Comment by kaiwalyakoparkar** [comment]
> 

Don't worry about it. It doesn't affect anything

**Comment by iqrafirdose** [comment]
> > Hey @kaiwalyakoparkar, can you please explain to me what greeting means failed? Why does it happen?
> 
> Don't worry about it. It doesn't affect anything

Ok.Again I need to create pull request or you will check if it is good then accept my pull request?

**Comment by kaiwalyakoparkar** [comment]
> > > Hey @kaiwalyakoparkar, can you please explain to me what greeting means failed? Why does it happen?
> > 
> > 
> > Don't worry about it. It doesn't affect anything
> 
> Ok.Again I need to create pull request or you will check if it is good then accept my pull request?

We will check your currently raised pr

**Comment by iqrafirdose** [comment]
> 

Ok @kaiwalyakoparkar .Thank you

**Comment by Vishvsalvi** [comment]
Let me work on this

**Comment by sajdakabir** [comment]
Hey @kaiwalyakoparkar i would like to work on this. Can I start working?

**Comment by AniketNS** [comment]
Hey, @kaiwalyakoparkar I really want to work on this issue. Please assign this to me.

**Comment by gaurav-16** [comment]
Hey, @kaiwalyakoparkar I would like to work on this issue. It would be really great if you can assign this issue to me!!!

**Comment by suryanshsoni120** [comment]
@kaiwalyakoparkar, I would like to contribute to this issue. Can I work?
