### ISSUE TITLE
[bug] The banner does not close.

### ISSUE THREAD

**Issue by SaadOps** [WeMakeDevs/wemakedevs#503]
### Describe the bug

The banner does not close because of the announcement image and events button.
It works fine without those two elements.

### Expected Behavior

The banner should close after clicking on the 'x' button.

### Screenshot/ Video

Not working with the announcement and events button. 
![image](https://user-images.githubusercontent.com/94478736/228802566-5e3d4090-0568-4648-8be6-d652c0a0d9b7.png)

Working after removing it.
![image](https://user-images.githubusercontent.com/94478736/228803474-51ab7667-56ba-42e9-9e8b-0410dabf3c56.png)
![image](https://user-images.githubusercontent.com/94478736/228803582-ef9f3651-3736-4af2-843f-3f2e95e47f0f.png)

**Comment by Sreejit-Sengupto** [comment]
Is anybody working on this?

**Comment by SaadOps** [comment]
I found out that it's not a bug and the banner closes after scrolling the page a bit, therefore I'm closing the issue.

**Comment by Sreejit-Sengupto** [comment]
Yes I noticed that too but I think it should close when the close button is clicked no matter what.
