### ISSUE TITLE
[bug] Guide link of a path not working on the hackathon page.

### ISSUE THREAD

**Issue by rootxrishabh** [WeMakeDevs/wemakedevs#510]
### Describe the bug

The guide [link](https://docs.napptive.com/tutorials/deploying_a_custom_application.html) for the "Migrate an open source application to the Open Application Model" path is not working.

### To Reproduce

1. Go to https://wemakedevs.org/events/hackathons/napptive#register

2. Scroll down to the Hackathon tracks.

3. Click on the guide [link](https://docs.napptive.com/tutorials/deploying_a_custom_application.html) of the first track.

### Expected Behavior

The link should redirect to an existing guide.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/73490663/229295756-69699e25-76de-45d6-a2c0-3dffa8ac203b.png)

**Comment by itshypon** [comment]
I think one of these links may replace it - 
https://docs.napptive.com/getting_started/deploy_first_app_from_catalog.html
https://docs.napptive.com/deploying_apps.html

**Comment by Chandraprakash-Darji** [comment]
Solved done

**Comment by Chandraprakash-Darji** [comment]
@itshypon @rootxrishabh thanks a lot for attention
