### ISSUE TITLE
Typos on the Napptive hackathon page

### ISSUE THREAD

**Issue by AnmolBansalDEV** [WeMakeDevs/wemakedevs#517]
### Describe the bug

Their are some minor typos on the hackathon page.

### To Reproduce

visit https://wemakedevs.org/events/hackathons/napptive

### Screenshot/ Video

typos are underlined.
<img width="953" alt="Screenshot 2023-04-01 232306" src="https://user-images.githubusercontent.com/86472377/229306735-32b5e73c-acf3-4ec6-bc83-09fd15e19725.png">

**Comment by Chandraprakash-Darji** [comment]
@AnmolBansalDEV which typo are you talking about

**Comment by AnmolBansalDEV** [comment]
Spelling of "using" in first and second card also it should be "win prizes" not "won prizes" in the subheading.

**Comment by Chandraprakash-Darji** [comment]
@AnmolBansalDEV thanks

**Comment by AnmolBansalDEV** [comment]
I closed the issue without the pr. I wanted to make a pr contribution 🥲
