### ISSUE TITLE
[bug]Telegram links does not work 

### ISSUE THREAD

**Issue by Bzsmrf** [WeMakeDevs/wemakedevs#518]
### Describe the bug

Telegrams links does not work if we do not have the telegram app already opened on our desktop/laptops  

### To Reproduce

Go to any page where their is telegram link 
Click on it 
It will show "This site cannot be reached"

### Expected Behavior

Telegram Links should lead us to the telegram App

### Screenshot/ Video

https://user-images.githubusercontent.com/92678867/229327328-c653fb6d-d875-4f30-9229-b3dc9862d99b.mp4

**Comment by AnuragThePathak** [comment]
t.me link also working fine in mine and I don't have telegram installed even.

**Comment by Bzsmrf** [comment]
Hey anurag I checked the  links on multiple devices(4) it works on some and doesn’t on some 
That’s why I thought of making an issue

**Comment by AnuragThePathak** [comment]
In which devices did it not work?

**Comment by Bzsmrf** [comment]
I did a bunch of stuff to find out why this is happening but found not proper explanation . I found out on reddit this is common issue faced by many. I firstly thought their might be some extensions on my device blocking it but I have no extensions as such. I checked this link on my classmates as well it doesn't work. I came to conclusion that it is possible that the link is not accessible in my region due to restrictions imposed by your internet service provider .

**Comment by AnuragThePathak** [comment]
@siddhant-khisty are you having any trouble as this issue? I tried on Mac and Android, no such issues encountered.

**Comment by siddhant-khisty** [comment]
@AnuragThePathak This works fine for me on all devices. The problem could be an ad blocker extension or some network settings.

**Comment by AnuragThePathak** [comment]
Ok then we should not be bothered.
