### ISSUE TITLE
Unnecessary repetition of a sentence on the Napptive's Hackathon page

### ISSUE THREAD

**Issue by kethesainikhil** [WeMakeDevs/wemakedevs#520]
### Describe the bug

under the hackathon tracks section there is a best use case blog post section in that there is an typo the 2nd point is repeated two times "Make sure to add #WeMakeDevs when publishing it on Hashnode".

### Expected Behavior

it should be written only one time

### Screenshot/ Video

![Screenshot (468)](https://user-images.githubusercontent.com/70809367/229347425-31c7e05d-453e-4ed8-8322-ead54f4f06dc.png)

**Comment by ShimpiTejas** [comment]
Hey, If this is not solved, Please Assign this to me

**Comment by kethesainikhil** [comment]
no solved @ShimpiTejas
