### ISSUE TITLE
[bug] Subscribe to newsletter email validation does not work

### ISSUE THREAD

**Issue by shawshankkumar** [WeMakeDevs/wemakedevs#538]
### Describe the bug

If I add an email shashank@kumar.com that works. If add shashankkumar, it shows an error. Very good. But If I add shashank@com, it accepts the email, while the email is not valid. Proper validation is needed. 

<img width="1744" alt="image" src="https://user-images.githubusercontent.com/74819565/230432181-5d845cda-c3ab-4caa-8321-022f5140acbd.png">

### To Reproduce

Go to https://wemakedevs.org/ 's join us and subscribe section. Enter shashank@com and it will work. 

### Expected Behavior

It should throw an error.

### Additional context

More than happy to work on this.

**Comment by shawshankkumar** [comment]
just noticed its embedded using iframes https://wemakedevs-newsletter.vercel.app/

Any reason why?

**Comment by AnuragThePathak** [comment]
Iframe is used because the subscription process is handled by hash node and I don't think we need to worry about email validation on our end, but yeah I'll confirm and work accordingly.

**Comment by shawshankkumar** [comment]
Imo, a good form should have validation on both, backend and frontend (
better ux)👀

You can close this issue. Cheers!

**Comment by AnuragThePathak** [comment]
Ya of course a good form should have that.

**Comment by munnokd** [comment]
Can I work on this issue?
