### ISSUE TITLE
Website Improvement: Redesigned work section on the homepage

### ISSUE THREAD

**Issue by harmanbatheja15** [WeMakeDevs/wemakedevs#539]
### Redesigned `work section` on the homepage

# Current Design
<img width="2240" alt="Screenshot 2023-04-07 at 1 39 17 AM" src="https://user-images.githubusercontent.com/66913564/230484293-46bbfb56-fc21-41a4-b453-97cf6344d06e.png">

# New Design
<img width="2240" alt="Screenshot 2023-04-07 at 2 12 48 AM" src="https://user-images.githubusercontent.com/66913564/230490014-8053b12e-a684-40f6-8ee5-45fb2222e5a0.png">

**Comment by HectorShaw** [comment]
yes the blue background makes sense but I don't see much of a problem with the `<hr class="styled-hr">`  as it seems they follow the common style guide for headers throughout the page. That is a good observation though.

**Comment by karthiknadar1204** [comment]
If this issue is still open,please assign it to me
