### ISSUE TITLE
[bug] Key is not passing properly to map function

### ISSUE THREAD

**Issue by hrutik7** [WeMakeDevs/wemakedevs#541]
### Describe the bug

in hackathon page . I observed that over some places unique key is not passing 

### To Reproduce

key must be unique so it will not show any error
![image](https://user-images.githubusercontent.com/62372737/230612389-383ec4d3-3404-457a-a2a8-a473f974a13a.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/62372737/230612410-90493272-660f-431f-ba2f-66a12a4876d7.png)

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/62372737/230611835-1ccad526-57cd-474a-b504-d0371cbc56c0.png)

**Comment by rajaditya06** [comment]
hai @hrutik7 i wanted to work on this issue, can u please assign it to me

**Comment by hrutik7** [comment]
I am not the maintainer of this repo
