### ISSUE TITLE
[bug] No scroll animation while navigating through different sections of the website 

### ISSUE THREAD

**Issue by Sreejit-Sengupto** [WeMakeDevs/wemakedevs#547]
### Describe the bug

No animation/transition while scrolling through different sections.

### Screenshot/ Video

https://user-images.githubusercontent.com/69980616/230782098-ae1e9ce8-bcba-4f26-b06c-04bd43fbd8e0.mp4

**Comment by Sreejit-Sengupto** [comment]
It's missing scroll-behaviour smooth in the html

**Comment by Sreejit-Sengupto** [comment]
@Chandraprakash-Darji am I supposed to create a PR? Or you can do the same and close this issue.

**Comment by Chandraprakash-Darji** [comment]
@Sreejit-Sengupto If you want, or other contributer can make it to. fix PR title
