### ISSUE TITLE
[bug] Duplicate Testimonials Text in the Website

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [WeMakeDevs/wemakedevs#552]
### Describe the bug

There is a duplicate **Testimonials** section in the website.

### To Reproduce

1. Go to [WeMakeDevs website](https://wemakedevs.org/).
2. Scroll down to **Events**.
3. Below **Events** section, a duplicate section of **Testimonials** can be found.

### Expected Behavior

There should be one **Testimonials** section in the website.

### Screenshot/ Video

[Recording_1681227568047.webm](https://user-images.githubusercontent.com/105960032/231218664-8195db7c-f34f-4f5a-bbd6-d3e84f6bba1b.webm)

### Additional context

**Browser** - _Microsoft Edge_
**OS** - _Ubuntu 22.10_

**Comment by SaptarshiSarkar12** [comment]
Can I work on this issue? @Chandraprakash-Darji @SuperAayush

**Comment by Chandraprakash-Darji** [comment]
@SaptarshiSarkar12 first one is course testimonial and another is event testimonial

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 first one is course testimonial and another is event testimonial

Okay, I understood. Then, the section names need to be changes to **Course Testimonials** and **Events Testimonials**. I think it will be better.
Also, the events testimonials is blank and has no content. Something needs to be done to fix that. Do you agree @Chandraprakash-Darji ?

**Comment by Chandraprakash-Darji** [comment]
@SaptarshiSarkar12 it is not loading in your side ig, But it is completly working on my side
Which browser you are using?
Name can fixed
![Screenshot 2023-04-12 at 2 25 10 PM](https://user-images.githubusercontent.com/93640141/231406294-79e5231d-9082-4814-8759-cbe4aa0690e1.png)

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 it is not loading in your side ig, But it is completly working on my side Which browser you are using? Name can fixed ![Screenshot 2023-04-12 at 2 25 10 PM](https://user-images.githubusercontent.com/93640141/231406294-79e5231d-9082-4814-8759-cbe4aa0690e1.png)

@Chandraprakash-Darji Yes, you are right. I was using Microsoft Edge browser on my laptop. When I openedthe website in chrome in mobile, I found that it is working.

**Comment by sanjivpaul** [comment]
> 

is your problem is solved or not?

**Comment by SaptarshiSarkar12** [comment]
> > 
> 
> is your problem is solved or not?

@sanjivpaul No, the events testimonials are not displayed in my laptop but it works fine on mobile although both devices are connected to the same network. I don't know the reason for this.

**Comment by sanjivpaul** [comment]
> > > 
> > 
> > 
> > is your problem is solved or not?
> 
> @sanjivpaul No, the events testimonials are not displayed in my laptop but it works fine on mobile although both devices are connected to the same network. I don't know the reason for this.

@SaptarshiSarkar12 can I work on this issue?

**Comment by Chandraprakash-Darji** [comment]
Edge browser not allowed to fetch the tweet, there is problem with edge

**Comment by HectorShaw** [comment]
> Edge browser not allowed to fetch the tweet, there is problem with edge

Brave facing the same issue

**Comment by Sreejit-Sengupto** [comment]
> > Edge browser not allowed to fetch the tweet, there is problem with edge
> 
> Brave facing the same issue 

It's working. It just takes some time to load.

**Comment by mhdamaan79** [comment]
It is working fine, and both Testimonials are showing no issues. I have checked it on Chrome, Edge, Firefox, and Brave.

**Comment by Sreejit-Sengupto** [comment]
Oh nice!

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak should we change the testinomial heading on homepage? becuse it is comfusing for people

**Comment by rohankumarchaudhary67** [comment]
> @AnuragThePathak should we change the testinomial heading on homepage? becuse it is comfusing for people

Try to merge the both testimonials because most of the testimonials are from Twitter users

**Comment by rohankumarchaudhary67** [comment]
> @AnuragThePathak should we change the testinomial heading on homepage? becuse it is comfusing for people

Try to merge the both testimonials because most of the testimonials are from Twitter users

**Comment by siddhant-khisty** [comment]
@Chandraprakash-Darji I believe we can change the heading to "Event winners"

**Comment by SaptarshiSarkar12** [comment]
> @Chandraprakash-Darji I believe we can change the heading to "Event winners"

Can I work on the issue @siddhant-khisty ?

**Comment by AnuragThePathak** [comment]
@SaptarshiSarkar12 go ahead

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 go ahead

ok :+1: @AnuragThePathak
