### ISSUE TITLE
[bug] Spelling error in Events page

### ISSUE THREAD

**Issue by sid-talesara** [WeMakeDevs/wemakedevs#571]
### Describe the bug

There is a spelling error in Kunal's designation on the Events page.

### To Reproduce

1. Go to events page.
2.  scroll and select ongoing events
3.  scroll to judges section

### Expected Behavior

Typo in spelling of Manger. It should be Manager

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/95763376/233775588-580fc3b1-01e6-4f4c-9bd6-7008559c16bc.png)

**Comment by rahulkanodia27** [comment]
Can I work on this issue?

**Comment by Sandeep-RN** [comment]
> Can I work on this issue?

Yes, 
Go ahead and open a PR for the same.

**Comment by rahulkanodia27** [comment]
but two more files must be changed ( IndividualWebinar/Speakers.jsx and Meetup/delhi-2023.js )

**Comment by Sandeep-RN** [comment]
> but two more files must be changed ( IndividualWebinar/Speakers.jsx and Meetup/delhi-2023.js )

Create a PR for that and do mention this Issue in the comment.

**Comment by Chandraprakash-Darji** [comment]
@rahulkanodia27 it is fixed in #578, I think we can close this because it PR is made and there is duplicate issue #577
