### ISSUE TITLE
[bug] Spelling error in Word Manager

### ISSUE THREAD

**Issue by Susmita-Dey** [WeMakeDevs/wemakedevs#577]
### Describe the bug

There is a spelling error in the word **"Manager** in 3 places of the website.

### To Reproduce

Replace "Manger" to "Manager"

**Comment by hemantwasthere** [comment]
Hey @Susmita-Dey, I would like to work on this issue

**Comment by Susmita-Dey** [comment]
> Hey @Susmita-Dey, I would like to work on this issue

It has been solved. Kindly look into other issues.
