### ISSUE TITLE
styling overflow 

### ISSUE THREAD

**Issue by hemantwasthere** [WeMakeDevs/wemakedevs#579]
### What would you like to share?

![image](https://user-images.githubusercontent.com/85151171/233841655-526694d5-a0a1-4611-acec-43084939b929.png)

This **INR 25000** section is causing a horizontal scroll in the mobile view `/events/hashnode` page.

**Comment by hemantwasthere** [comment]
I would like to work on this issue

**Comment by Chandraprakash-Darji** [comment]
@hemantwasthere thanks for the issue, go for it, I will recommend you make it width full.
