### ISSUE TITLE
[bug]: Testimonial Section - Missing Tweet causing Layout Issue

### ISSUE THREAD

**Issue by Arindam200** [WeMakeDevs/wemakedevs#582]
### Describe the bug

In the testimonial section of this website, there is a layout issue where one tweet is not displaying, causing the testimonial cards to appear incomplete and unbalanced. This is affecting the overall visual appearance and user experience of the section.

### Expected Behavior

The testimonial section should display all the tweets in a visually appealing layout, with all testimonial cards showing complete content and maintaining a balanced design.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/109217591/234052957-0c1ab30c-0a89-41e8-938e-7acddf7d3b4e.png)

**Comment by Chandraprakash-Darji** [comment]
@Arindam200 on which page it is happening?

**Comment by Arindam200** [comment]
On the First Page of ```https://wemakedevs.org/courses#testimonials```

**Comment by Manjeshkgp** [comment]
Would you please allow me to work on this issue
