### ISSUE TITLE
sitemap.xml is  missing

### ISSUE THREAD

**Issue by coder-harsh** [WeMakeDevs/wemakedevs#584]
### What would you like to share?

Sitemap.xml is missing. A sitemap file helps google crawl the website better and it helps to index all the links of the website. please assign me this issue.

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji do you suggest closing it or keeping it?

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak Let's just close it
