### ISSUE TITLE
[bug]: Related to padding

### ISSUE THREAD

**Issue by Mohiit70** [WeMakeDevs/wemakedevs#585]
### Describe the bug

The issue appears to be related to the padding, which seems to be causing some display problems.
https://wemakedevs.org/events/hashnode

### Screenshot/ Video

https://user-images.githubusercontent.com/120316966/234325809-0e663926-9f0b-477d-baef-d00a8fb9234f.mp4

![Screenshot (38)](https://user-images.githubusercontent.com/120316966/234326054-dbd93878-3e38-477e-b2ee-80983935eb5f.png)

**Comment by manthanindane** [comment]
can I work on this issue?

**Comment by Mohiit70** [comment]
> can I work on this issue?

Yes you can

**Comment by debmalya37** [comment]
hey , can I take on this issue ??

**Comment by Chandraprakash-Darji** [comment]
This is solved already
