### ISSUE TITLE
[bug] Carousel elements should be centered

### ISSUE THREAD

**Issue by MitAbhay** [WeMakeDevs/wemakedevs#595]
### Describe the bug

I found that most of the carousel elements are not centered in the site, for better UI it should be centered.

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/76659113/236665856-73d443b1-a63d-4245-ab46-703f99df7633.png)
![image](https://user-images.githubusercontent.com/76659113/236665903-f6fec0f0-0e20-4be0-8b42-b4960754da30.png)

**Comment by AnuragThePathak** [comment]
I think this fine considering these are last frames in their respective category. What do you think @Chandraprakash-Darji

**Comment by Chandraprakash-Darji** [comment]
@MitAbhay can you explain better?
