### ISSUE TITLE
Super25 page cursor issue

### ISSUE THREAD

**Issue by Ghat0tkach** [WeMakeDevs/wemakedevs#597]
### What would you like to share?

In the super 25 page , when navigating through the benefits the cursor automatically changes into pointer , 
Since its just bout the benefits not any external link , we could probably remove the cursor :pointer or maybe add some hovering effects while navigating.

https://user-images.githubusercontent.com/59855919/237008857-7639b9dc-53c6-4cd9-9819-6126f93f0026.mp4

**Comment by siddhigate** [comment]
Hey, @Ghat0tkach That's a good catch. Let's remove the cursor point from the cards. Assigning it to you.
