### ISSUE TITLE
[typo] Spelling of Stipend incorrect in Super25 FAQ page

### ISSUE THREAD

**Issue by OMGATE23** [WeMakeDevs/wemakedevs#600]
### What would you like to share?

The spelling of the word stipend in one of the FAQ questions is incorrect
![image](https://github.com/WeMakeDevs/wemakedevs/assets/90276220/e5f856da-52b0-4247-9092-556fd0d1223b)

**Comment by OMGATE23** [comment]
Can you please assign this issue to me?

**Comment by GunjanKMishra** [comment]
Hey, I want to work on this issue can you please assign it to me? I'm new to open-source contributions.

**Comment by P-4-PRATYUSH-RANJAN** [comment]
new to open souce but still never giving up

**Comment by qrex19** [comment]
hey, I would like to make my contributions to this project, can you assign it to me??
