### ISSUE TITLE
[bug] Accessibility Issues in the "Our students at work" section

### ISSUE THREAD

**Issue by inclinedadarsh** [WeMakeDevs/wemakedevs#603]
### Describe the bug

There is an accessibility issue in the title in the "Our Students at work" section.
![image](https://github.com/WeMakeDevs/wemakedevs/assets/84132532/9b7f8399-2625-4d61-bbab-a8dd1bad5d0e)

The current contrast of text w.r.t background is 1.26:1 and the minimum requirements according to the W3 Guidelines it should be at least 3:1 for large texts.

**Comment by Lucif3r-in** [comment]
Hello @siddhigate @Manjeshkgp  , Can you check the issue? If reasonable can I work on it?

**Comment by Manjeshkgp** [comment]
I'll try my best to check it

**Comment by siddhigate** [comment]
@Lucif3r-in you can work on it. Are you able to reproduce the issue?

**Comment by Lucif3r-in** [comment]
> @Lucif3r-in you can work on it. Are you able to reproduce the issue?

No I guess there is no such issue!! Color is fine when I reproduced it. This issue can be closed.

**Comment by siddhigate** [comment]
> > @Lucif3r-in you can work on it. Are you able to reproduce the issue?
> 
> No I guess there is no such issue!! Color is fine when I reproduced it. This issue can be closed.

this issue occurs when by default the browser doesn't have dark mode. the current classes used are `text-gray-800 dark:text-gray-300` it should be `text-gray-300 dark:text-gray-300`

**Comment by siddhigate** [comment]
> So changing to `text-gray-300 dark:text-gray-300` will solve the issue right? @siddhigate

Yes it will
