### ISSUE TITLE
[feat] Add Open Graph meta tags 

### ISSUE THREAD

**Issue by Lucif3r-in** [WeMakeDevs/wemakedevs#605]
### Would you like to have a new feature? Please describe.

Whenever I try to share WeMakeDevs website, I get to see a simple link with a title, which doesn't look much appealing.

![image](https://github.com/WeMakeDevs/wemakedevs/assets/85403534/7644dec4-a1c0-4377-935d-3c313b503197)

### How would this feature be beneficial for the project

Adding meta tags with a image, description, title and other Open Graph meta tags may improve the way the post would look when shared. Attaching example below.

### Additional context

![image](https://github.com/WeMakeDevs/wemakedevs/assets/85403534/3b441cc9-8cca-4208-8da9-74ee904a3694)

##P.S - I would like to work on this issue.

**Comment by Lucif3r-in** [comment]
@siddhigate @Manjeshkgp Can I work on this issue?

**Comment by hemantwasthere** [comment]
I would also love to work on this issue

**Comment by Lucif3r-in** [comment]
@siddhigate Can you please review my PR #606
