### ISSUE TITLE
Side Arrows on Testimonials ,Events Winners

### ISSUE THREAD

**Issue by nayan-dey** [WeMakeDevs/wemakedevs#607]
### What would you like to share?

![Screenshot 2023-05-14 133807](https://github.com/WeMakeDevs/wemakedevs/assets/133354699/045e986d-4881-4c43-bf29-0c160869781d)
side arrows are in top of the cards.
I want to fix this issue

### Additional information

also it won't support any gestues whil slide from left to right or vice versa. I can fix it but how can i contribute? 
I need some help with this.Thank you

**Comment by krutagna10** [comment]
That is not an issue, they are styled this way

**Comment by nayan-dey** [comment]
> That is not an issue, they are styled this way

Yeah I completely agree with you.
But I learned the codebase and found that "Better React Carousel" is the library behind all the corousal on the app. and in the library there were two props calls

**Comment by nayan-dey** [comment]
I completely agree with you but I learned the codebase and found that "Better React Carousel" is the library behind all the corousal on the app. and in the library there were two props called "arrowLeft" and "arrowRight". And if you add these props you can customise the arrows way you want. Right now I'm working on it. hopefully it would look better.
