### ISSUE TITLE
How to npm start into a non default browser?

### ISSUE THREAD

**Issue by coder-XX04** [WeMakeDevs/wemakedevs#609]
When using the command ` npm start ` it opens the wemakedevs webpage at **localhost:3000** in the default browser of the system. 

How can I open the wemakedevs in a **non-default browser like Firefox developer edition** from `npm start` and with a different port other than localhost:3000?

**Comment by nayan-dey** [comment]
you can just copy url and open in wherever you wants to.

**Comment by coder-XX04** [comment]
@nayan-dey yes that works, but my issue is to stop opening automatically into the default browser when use `npm start` but to open in a non-default browser .

**Comment by nayan-dey** [comment]
Just

> @nayan-dey yes that works, but my issue is to stop opening automatically into the default browser when use `npm start` but to open in a non-default browser .

Just change the default browser to the browser you wants to. If you can't... just Google it or ask gpt your problem, it will surely help you. Thanks

**Comment by coder-XX04** [comment]
OK, let me try thanks for the help.
