### ISSUE TITLE
[feat]

### ISSUE THREAD

**Issue by giteshsarvaiya** [WeMakeDevs/wemakedevs#611]
### Would you like to have a new feature? Please describe.

It would be much fascinating and exciting is these numbers are real-time generated via API calls from respected services..
![Screenshot_20230517_141718_Chrome](https://github.com/WeMakeDevs/wemakedevs/assets/99144191/502cbbe0-b154-441b-a3d1-f59a90d12dff)

### How would this feature be beneficial for the project

This feature will make the website more fascinating and justify that the community of developers and for developers / computer science enthusiasts. 

### Additional context

It can be done via API calls from those respective services. 
Example , total YouTube views can called via Youtube API 
Total members can be called via API calls from discord server.. and so on.

**Comment by giteshsarvaiya** [comment]
I would be happy to contribute to this. 
This issue is small but will enhance overall techy vibe of the website

**Comment by AnuragThePathak** [comment]
@giteshsarvaiya our website do not have a backend component to use those APIs unfortunately.

**Comment by giteshsarvaiya** [comment]
Closing this as the website has no backend.
