### ISSUE TITLE
[Enhancement] of FAQ component

### ISSUE THREAD

**Issue by shivkumarojha** [WeMakeDevs/wemakedevs#614]
### What would you like to share?

FAQ component has 6 accordions which is divided into 2 parts of 3 each, In large devices it is divided into two grid columns, and clicking on both sides expands the accordion separately on both columns which are good, but when it comes to small devices like smartphones the grid changes into one column even in one column the Accordion's behavior is same. In small devices, either one of those 6 needs to open, and after clicking on another accordion the previous one needs to be closed.
[behaviour of FAQ accordion.webm](https://github.com/WeMakeDevs/wemakedevs/assets/40659426/86bafc66-2250-41b9-adbb-66224ffede46)

**Comment by 007AnupamSharma** [comment]
assign it to me, I'll do this according to your suggestion

**Comment by AnuragThePathak** [comment]
@007AnupamSharma I've assigned it you, commit the required changes and let us know if you are stuck anywhere.

**Comment by 007AnupamSharma** [comment]
Ok

**Comment by Varghab** [comment]
@007AnupamSharma This is happening because two Accordion components are rendered, it would work perfectly if only one Accordion component is rendered.

**Comment by 007AnupamSharma** [comment]
Ok I'll check

**Comment by 007AnupamSharma** [comment]
please check and tell me whether is it ok or not.
