### ISSUE TITLE
[feat] Adding Design on the buttons

### ISSUE THREAD

**Issue by bishal7679** [WeMakeDevs/wemakedevs#62]
### Would you like to have a new feature? Please describe.

Want to add some design on the buttons.

See this video once

https://user-images.githubusercontent.com/70086051/197324529-3d9c75a6-6080-4f18-a33f-370708224f5f.mp4

https://user-images.githubusercontent.com/70086051/197327062-8a9d1c98-1848-4d03-8a4a-17bafa078bbb.mp4

**Comment by kaiwalyakoparkar** [comment]
@SuperAayush @bhavyastar please take a look and confirm if this change conflicts with the changes in the roadmap

**Comment by SuperAayush** [comment]
Hey @bishal7679!!
You can go for a PR.
