### ISSUE TITLE
[perf] code splitting for lazy loading scholarships, hackathons, educational events page

### ISSUE THREAD

**Issue by siddhigate** [WeMakeDevs/wemakedevs#620]
### What would you like to share?

The implementation of code splitting using React's lazy loading technique to improve the performance and loading times of our scholarships, hackathons, and educational events pages. By implementing code splitting, we can dynamically load these pages only when they are actually requested by the user, rather than loading them all upfront.

**Comment by Lucif3r-in** [comment]
@siddhigate I would like to contribute to it. Can you suggest me where to look into.

**Comment by Lucif3r-in** [comment]
> Individual page-level component's performance must be measured before keeping changes

Sure! Will check that!!
