### ISSUE TITLE
Changes in events page

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#621]
Main page:
- [x] #631
- [x] #630
    - $20,000+ prizes
    - 30,000+ participants
    - 30+ countries
    - 200,000+ empowered
- [x] #629

- [x] #650
  - [x] Add Past in the header
  - [x] Add testimonials specific to this page
  - [x] #653
  - [x] Add a past meetups section. In the card, add the link to the main page for that meetup with title along with month + year + location. For now add one card, for Delhi meetup. Change URL to /delhi-may-2023. Also remove register option from dedicated event page of Delhi may.
  - [x] Add another card for this meetup: https://www.youtube.com/watch?v=6AQ7-LDcStM, just link to the learn more button in this card to this video. Add a thumbnail and same format as other cards.
  - [x] Edit [this page](https://wemakedevs.org/events/meetups/delhi-2023), remove registration, add [photos](https://photos.google.com/share/AF1QipP2V8b6Gbod-NV32ZIO1BL6A3ZdaFh13A5dbNQz9s5DYeuJbf81nkjEiC9oD90YiA?pli=1&key=cDROWmlvZjM4cVlJbXZnc19WWk42RlozTms4bUt3) from the events.

Hackathons page:
- [x] #637
- [x] #634
- [x] #628

Scholarship page:
- [x] #632

Educational page
- [x] #633

**Comment by hemantwasthere** [comment]
Would love to work on this issue, will let you know as soon as PR gets created.

**Comment by Parvej2001** [comment]
okay good luck @hemantwasthere 👍

**Comment by deveshgoyal1000** [comment]
Can work on this happily.

**Comment by Lucif3r-in** [comment]
@siddhigate @Parvej2001 Is there any part I can work on?

**Comment by siddhigate** [comment]
> @siddhigate @Parvej2001 Is there any part I can work on?

@Lucif3r-in you can pick up any of the not completed tasks from the list

**Comment by Lucif3r-in** [comment]
> > @siddhigate @Parvej2001 Is there any part I can work on?
> 
> @Lucif3r-in you can pick up any one of the not completed tasks from the list

Sure.

**Comment by ashutosh887** [comment]
I would like to work on this as well @siddhigate @kunal-kushwaha @SuperAayush

**Comment by kunal-kushwaha** [comment]
awesome work
