### ISSUE TITLE
Add testimonials on Educational page

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [WeMakeDevs/wemakedevs#633]

**Comment by hemantwasthere** [comment]
Hey @Chandraprakash-Darji , Would love to add testimonials on Educational page also

**Comment by hemantwasthere** [comment]
@Chandraprakash-Darji, I was addressing this issue, but I noticed that there is already a dedicated segment of **Testimonials** featured on the **Educational** page.

**Can you please check**
![image](https://github.com/WeMakeDevs/wemakedevs/assets/85151171/541f0701-1ea2-4b24-bb0b-9d3ef3ee7108)

**Comment by AnuragThePathak** [comment]
@hemantwasthere I hope you are willing to work on this issue (a confirmation will be appreciated) since you expressed interest on it earlier and hence assigned you. First, you fix this one asap and then we will see about the KubeCon one.

**Comment by anongorax** [comment]
I'll volunteer for the backup if there is any urgency.

**Comment by AnuragThePathak** [comment]
@anongorax how long would you need?

**Comment by anongorax** [comment]
@AnuragThePathak 1-2 hours

**Comment by anongorax** [comment]
Should I start working?

**Comment by AnuragThePathak** [comment]
@anongorax all right, you can start working probably. @hemantwasthere will work on the other issue once the testimonials are available.

**Comment by anongorax** [comment]
@AnuragThePathak  Question: where do we want the new Testimonial component in the `event/hashnode` page since in the bottom there exists same title?

**Comment by anongorax** [comment]
Alright a new section!

**Comment by AnuragThePathak** [comment]
@anongorax the page that you need to update is events/educational page. It doesn't have a community testimonial section. So you need to add that and that's all about this issue.

**Comment by anongorax** [comment]
Thanks for the clarification @AnuragThePathak

**Comment by AnuragThePathak** [comment]
@anongorax let me know if you need any other help.

**Comment by anongorax** [comment]
Thanks @AnuragThePathak , I'm almost done.

**Comment by anongorax** [comment]
@AnuragThePathak, 
I would like to inform you that I have successfully integrated the component into the Educational page as requested. In addition, I have included the tweets specified in the following link: [comment #633](https://github.com/WeMakeDevs/wemakedevs/issues/633#issuecomment-1597335355).

To provide you with an overview of the current state, I have attached a screenshot below. Please review the displayed content and let me know if there is a need for additional tweets or if you would like me to search for more relevant tweets to incorporate into the carousel.
![Screenshot from 2023-06-20 12-50-15](https://github.com/WeMakeDevs/wemakedevs/assets/34363697/c8b8bb9f-cd99-44c6-a90b-bd1a0d8b8fba)

**Comment by anongorax** [comment]
@AnuragThePathak in tweets people have tagged commclassroom, I have to change it to WeMakeDevs right ?

**Comment by AnuragThePathak** [comment]
@anongorax for now just create the PR for testimonials (design is the prime concern for now). We can think about these later.

**Comment by hemantwasthere** [comment]
:)
