### ISSUE TITLE
[feat] New scroll bar for newsletter section (for mobile)

### ISSUE THREAD

**Issue by Varghab** [WeMakeDevs/wemakedevs#635]
### Would you like to have a new feature? Please describe.

When viewed on mobile, a default scroll bar is used for the newsletter section. A scrollbar similar to that used for the website would make the newsletter section elegant. **I can fix this, please assign me this if not anyone working on it yet.**

**Current scroll bar -** 

![Screenshot 2023-05-24 224714](https://github.com/WeMakeDevs/wemakedevs/assets/59419650/bc358e50-38fb-40b9-8f79-000c9708bf4a)

**Expected scroll bar -**

![Screenshot 2023-05-24 225426](https://github.com/WeMakeDevs/wemakedevs/assets/59419650/5562c108-e1ef-4f73-a6cc-ff2b430452dc)

**Comment by AnuragThePathak** [comment]
Is this the homepage or different one? My homepage do not have a dedicated scrollbar for newsletter section though.

**Comment by Varghab** [comment]
@AnuragThePathak The scroll bar shows up in mobile view

**Comment by AnuragThePathak** [comment]
Yeah I was talking about mobile view only, tested in my android phone.

**Comment by Varghab** [comment]
@AnuragThePathak I tried in my android phone and it also doesn't show up in my phone but when I tried to view it using inspect element for different devices there the scroll bar was visible. Maybe just disabling the overflow would do the job.

**Comment by AnuragThePathak** [comment]
@Varghab what in dimension did the scroll bar appear in inspect mode?

**Comment by Varghab** [comment]
@AnuragThePathak 
From this dimension scroll bar starts to show up
![dimension](https://github.com/WeMakeDevs/wemakedevs/assets/59419650/de505429-0477-47e9-90f0-92f284114bd2)

**Comment by AnuragThePathak** [comment]
@Chandraprakash-Darji would you like to confirm if whatever he mentioned is happening to you or not?

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak It is happening in smaller mobile, it can be fixed only by using native elements rather then iframe. It is future thing.

**Comment by AnuragThePathak** [comment]
@Varghab closing it as it requires extensive changes.

**Comment by Varghab** [comment]
@AnuragThePathak It can be fixed by setting the iframeheight to somewhere around 1030 if the windowwidth is less than 900, try once!
