### ISSUE TITLE
[bug] Overlapping of the scroll top arrow on mobile devices

### ISSUE THREAD

**Issue by SuyashPatil-29** [WeMakeDevs/wemakedevs#636]
### Describe the bug

Overlapping of the "scroll to top" and the "Checkout our upcoming events" tab on both the mobile view and larger view.

![wemakedevs_mobile](https://github.com/WeMakeDevs/wemakedevs/assets/112413583/d8299039-6e19-4257-a8fa-d8f891e99511)

🔝 for the mobile view 

![image](https://github.com/WeMakeDevs/wemakedevs/assets/112413583/28e424e7-5797-4c6b-a53f-5ad958956273)

🔝 for the larger view ie laptops

### Screenshot/ Video

![wemakedevs_mobile](https://github.com/WeMakeDevs/wemakedevs/assets/112413583/20e34d74-a2d4-4d13-b4f4-cbf6aa03cb70)

![image](https://github.com/WeMakeDevs/wemakedevs/assets/112413583/15e02911-035e-4aa0-a198-729bd543a49e)

**Comment by SuyashPatil-29** [comment]
I would love to solve the issue. Maintainers please assign.

**Comment by SuyashPatil-29** [comment]
The issue has been resolved @AnuragThePathak

**Comment by AnuragThePathak** [comment]
@kondebonimahesh chats in this is issue should be limited to the issue-related discussions only, you may ask me this sort of questions somewhere else like WeMakeDevs discord server or my Twitter.

**Comment by SuyashPatil-29** [comment]
I think this issue can be closed now.
