### ISSUE TITLE
Add testimonials on Hackathons

### ISSUE THREAD

**Issue by Chandraprakash-Darji** [WeMakeDevs/wemakedevs#637]

**Comment by Lucif3r-in** [comment]
@Chandraprakash-Darji I would like to work on this issue. Can you please guide me to the contents for the testimonials?

**Comment by Chandraprakash-Darji** [comment]
Go ahead @Lucif3r-in

**Comment by Lucif3r-in** [comment]
@Chandraprakash-Darji I can see a sponsor testimonial on every page. What to do about it?
And where to get the content for the hackathon testimonials?

**Comment by Chandraprakash-Darji** [comment]
@Lucif3r-in it will like tweet testimonials. when you go on twitter when hackathon was organized, people was tweeting about it

**Comment by Lucif3r-in** [comment]
Is it similar to Events Winners section on the homepage? @Chandraprakash-Darji I am not getting how to fetch the tweets.

**Comment by Chandraprakash-Darji** [comment]
@Lucif3r-in there is already component where we just have to pass the tweetids

**Comment by Lucif3r-in** [comment]
> @Lucif3r-in there is already component where we just have to pass the tweetids
> 

Actually there were not much tweets so I had to take some testimonials from LinkedIn too
