### ISSUE TITLE
[other] : Style improvement in discord and telegram detail section

### ISSUE THREAD

**Issue by md-abid-hussain** [WeMakeDevs/wemakedevs#642]
### What would you like to share?

In screen with smaller viewport the top left and right of section get curved. However it is normal in case of screen with large viewport.

It can be improved by changing the styles in **JoinUsCard** which is inside **src/components/layout/JoinUs/Index.jsx** 

![wemakedevs org_](https://github.com/WeMakeDevs/wemakedevs/assets/101964499/5867e2a1-442c-4a26-8a05-5b9db424c662)

**Comment by Varghab** [comment]
Assign this task to me if no one is working on it yet.

**Comment by Chandraprakash-Darji** [comment]
@Varghab All the best

**Comment by md-abid-hussain** [comment]
Do we have to work before getting issue assigned?

**Comment by Chandraprakash-Darji** [comment]
@md-abid-hussain never work before issue is assigned
