### ISSUE TITLE
Open source course page

### ISSUE THREAD

**Issue by kunal-kushwaha** [WeMakeDevs/wemakedevs#680]
URL: http://wemakedevs.org/courses/opensource

- Header
- About section
    - Paragraph
    - Video embed (put random video for now)
- Who should join
- Why open source is important
- Course structure
    - Regular structured lectures that you can follow along
    - Interaction with industry experts to get you started in various domains on tech, learn from the maintainers directly
    - Assignments will be updated on the GitHub repo
    - We will also share free structured learning resources for various tech stacks, link our roadmaps repo for this.
    - Support in applying to open source programs like Google Summer of Code, Outreachy, Major League Hacking Fellowship, LFX, and more.
    - Add two buttons
        - YouTube playlist: https://www.youtube.com/playlist?list=PL9gnSGHSqcnq3Px3IAYF7yxeWGWrSdHK8
        - GitHub repo for assignments: https://github.com/WeMakeDevs/open-source-course
- Learn in public
    - Use #OpenSourceWithKunal on Twitter and share your journey regularly
    - Also mention here like, tie this in with blogging challenges we run and mention amazing prizes we give
- Testimonials
- Registration form (Kunal sent you on Discord)
- FAQ 
- Join + Newsletter

**Comment by Sreejit-Sengupto** [comment]
Can I work on this issue too?
