### ISSUE TITLE
[feat] Update the Google logo on the homepage.

### ISSUE THREAD

**Issue by Subgor8126** [WeMakeDevs/wemakedevs#687]
### Would you like to have a new feature? Please describe.

The Google logo on the homepage of the website is outdated. Update the google.svg file in the src/assets/home/company repository.

### How would this feature be beneficial for the project

Using the new logo will make the website look more updated.

### Additional context
![Screenshot (554)](https://github.com/WeMakeDevs/wemakedevs/assets/91906711/cd4a69d6-7523-4003-9d06-4122cd12d1ef)
)

_No response_

**Comment by ItIsOHM** [comment]
Hey @Subgor8126, I'd like to work on this issue as a beginner contributor. May I start working on it?

**Comment by Ansalpandey** [comment]
Hey @Subgor8126, Can you assign this issue to me?
