### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by Kevinkp09** [WeMakeDevs/wemakedevs#693]
### Describe the bug

1.There's a section on the open source course page on who should join this course. There's an english error in it. It says <b>"who should you join this course" </b>
<br/>

2.And also there's a grammatical mistake on the learn in public section that says <b>"There will be a [blogging challenge](https://wemakedevs.org/events/hashnode) will be running along with this and win exciting prices"</b> 

Please correct it

### Expected Behavior

1. It should be <b>"who should join this course"</b> or maybe <b>"why should you join this course"</b>

2. It should be <b>"There will be a [blogging challenge](https://wemakedevs.org/events/hashnode) that will be running along with this and win exciting prices" </b>

### Screenshot/ Video

<img width="1440" alt="Screenshot 2023-06-29 at 4 47 47 PM" src="https://github.com/WeMakeDevs/wemakedevs/assets/93664160/fe451d05-e881-4ee6-8b60-326fb9a970a4">

<br/>

<img width="1440" alt="Screenshot 2023-06-29 at 5 39 30 PM" src="https://github.com/WeMakeDevs/wemakedevs/assets/93664160/cd763b27-ae6d-4f6f-b670-4528cdf49143">

**Comment by AnuragThePathak** [comment]
Create a separate issue for the 2nd one, first one completed by #688
