### ISSUE TITLE
[bug] Site is not secure anymore 

### ISSUE THREAD

**Issue by KaKashi1210** [WeMakeDevs/wemakedevs#697]
### Describe the bug

site is not secure i guess ssl / tsl certificate is not valid anymore 
![image](https://github.com/WeMakeDevs/wemakedevs/assets/97914006/8aea3cca-d21d-442e-a08e-42ecc2928a7a)

**Comment by AnuragThePathak** [comment]
For me it's still secure, can you recheck it?

**Comment by KaKashi1210** [comment]
its working now they have fixed ssl certificate ig
