### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Kevinkp09** [WeMakeDevs/wemakedevs#699]
### Describe the bug

There's a grammatical mistake on the open source course page in the learn in public section. It says <b>"There will be a [blogging challenge](https://wemakedevs.org/events/hashnode) will be running along with this and win exciting prices"</b>

### Expected Behavior

Instead it should be  <b>"There will be a [blogging challenge](https://wemakedevs.org/events/hashnode) that will be running along with this and win exciting prices" </b>

### Screenshot/ Video

<img width="1440" alt="Screenshot 2023-06-29 at 5 39 30 PM" src="https://github.com/WeMakeDevs/wemakedevs/assets/93664160/11908449-9f0e-4983-a291-f33a2af87a66">

**Comment by Pravesh-Sudha** [comment]
I would like to fix this

**Comment by omkute** [comment]
if this issue is still open I would like to fix it
