### ISSUE TITLE
[FEATURE]: <Add FAQ Section>

### ISSUE THREAD

**Issue by yashsehgal** [WeMakeDevs/wemakedevs#7]
To create an FAQ section for the website, as shown in the design screenshot below
<img width="1470" alt="Screenshot 2022-10-14 at 8 45 15 AM" src="https://user-images.githubusercontent.com/62352288/195754331-a5cf3475-bdb7-4cc9-a6a2-290f858853f1.png">

**Comment by asdsyd** [comment]
I would like to work on this. Please add hacktoberfest label. Thanks.

**Comment by Rishav1707** [comment]
Can I work on this issue?? @yashsehgal

**Comment by boradesanket13** [comment]
Can I work on this issue, if it is open?
