### ISSUE TITLE
[bug] Website SSL Certificate Not Install Properly 

### ISSUE THREAD

**Issue by SagarDhadke** [WeMakeDevs/wemakedevs#701]
### Describe the bug

Dear WeMakeDevs Team,

We wanted to bring to your attention an important matter regarding your website's security.

Upon visiting your website, we noticed that it does not currently have a valid SSL certificate installed. An SSL certificate is crucial for ensuring a secure connection between your website and its visitors. Without a valid SSL certificate, sensitive information such as usernames, passwords, and other personal data transmitted through your website may be at risk of interception by malicious entities.

To address this issue, we strongly recommend obtaining an SSL certificate as soon as possible. We understand that cost can be a concern, but we have good news for you. Cloudflare, a reputable and trusted provider, offers free SSL certificates that can easily be installed on your website.

To obtain your free SSL certificate, we encourage you to visit the Cloudflare website at https://www.cloudflare.com/. Cloudflare provides a straightforward process for securing your website with an SSL certificate, and their services are widely recognized for their reliability and security.

By installing an SSL certificate, you will not only enhance the security of your website but also gain the trust and confidence of your visitors. It is essential in today's digital landscape to prioritize the privacy and protection of user data.

Please take action promptly to secure your website with an SSL certificate. If you require any assistance or have any further questions, do not hesitate to reach out to us.

Thank you for your attention to this matter. We wish you the best in ensuring the security of your website and the protection of your visitors' information.

Sincerely,

Sagar Dhadke

### Screenshot/ Video

![image](https://github.com/WeMakeDevs/wemakedevs/assets/70995022/0f6ee7a8-660c-4705-be0b-cbd617d9522b)

**Comment by KaKashi1210** [comment]
Its fixed now ig

**Comment by SagarDhadke** [comment]
@KaKashi1210 No Same Issue, Please Check http://wemakedevs.org/ it's not going to HTTPS Use Cloudflare 
for valid SSL Certificate, Cloudflare have one feature is For Always Use HTTPS 

Please Read Cloudflare Official Docs  :- https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/

**Comment by itsarraj** [comment]
@kunal-kushwaha @kaiwalyakoparkar I got banned from wemakedev discord please unban me , my user id 1063977934051885056

**Comment by itsarraj** [comment]
![image](https://github.com/WeMakeDevs/wemakedevs/assets/69187344/1614f8ea-5d8b-49a9-86ca-c8f9bfd45e8c)

**Comment by anongorax** [comment]
> @kunal-kushwaha @kaiwalyakoparkar I got banned from wemakedev discord please unban me , my user id 1063977934051885056

Do you think this is the right place to spam ?

**Comment by itsarraj** [comment]
@anongorax Help me where should i message ?
