### ISSUE TITLE
Redirecting User to YouTube  from wemakedevs website from syllabus

### ISSUE THREAD

**Issue by Ridhvisaikasam** [WeMakeDevs/wemakedevs#707]
### Would you like to have a new feature? Please describe.

https://wemakedevs.org/courses/devops
Under the syllabus section we can just redirect the user to YouTube video on clicking the topic , because this way of navigating is easier

### How would this feature be beneficial for the project

Easier navigation , and also website viewers surely go to YouTube channel
Obviously people come from YouTube to website , but still it would be beneficial.

**Comment by Aman254** [comment]
hey @Ridhvisaikasam can please specify the folder of this codebase.

**Comment by Aman254** [comment]
Hey @Ridhvisaikasam can you please Assign this to me. I will be adding the youtube links

**Comment by AnuragThePathak** [comment]
@Aman254 you may start working.

**Comment by Aman254** [comment]
Sure @AnuragThePathak

**Comment by Aman254** [comment]
hey @AnuragThePathak I, am done with adding the Enhancement of edirecting: 
User to YouTube from wemakedevs website from syllabus.  

Can you please provide links of the videos like: 
1. Servers 
2. Service mesh
3. Cloud native tools deep dive 
4. Testing
5. Monitoring and logging
6. GoLang
7. Working with cloud providers

Can you Please Provide me the video link to these videos as I searched on kunal Kushwah website but didn't found it.

**Comment by AnuragThePathak** [comment]
There are no videos on those probably.

**Comment by Aman254** [comment]
hey @AnuragThePathak Shall I Leave a empty video link so that later we can add the links when they are available

**Comment by AnuragThePathak** [comment]
Handing over to @siddhant-khisty

**Comment by Aman254** [comment]
hey @siddhant-khisty Can you please review my code for the issue: https://github.com/WeMakeDevs/wemakedevs/issues/707

**Comment by siddhant-khisty** [comment]
Hey @Aman254 you are right. The videos for the topics you've mentioned have not been created yet.

There are plenty of cloud-native tools deep dives, but those are based on individual tools, and I don't think a playlist has been created for those. At best you could add the link to this [webinars playlist](https://www.youtube.com/playlist?list=PL9gnSGHSqcnoCOwAA_5cYZ3eX_FF0Q1Mt)

I believe it would be best to add the link to the entire [DevOps Playlist](https://www.youtube.com/playlist?list=PL9gnSGHSqcnoqBXdMwUTRod4Gi3eac2Ak) for the links that don't exist yet.

**Comment by Aman254** [comment]
Ok @siddhant-khisty But, What I say is the links which are available are part of Devops Playlist, and I left an Empty String place wherein you can add the links whenever they are available, this is what I think please guide me If my approach is Wrong 

as am beginner, and I removed the .idea files which you asked to do. and made a commit.

**Comment by siddhant-khisty** [comment]
@Aman254 I think that is fine, but having a link to the core playlist would be better IMO. Some folks might keep trying to click the topics but wouldn't get redirected anywhere which might get confusing

**Comment by Aman254** [comment]
Sure @siddhant-khisty I, will be adding that now.

**Comment by Aman254** [comment]
> @Aman254 I think that is fine, but having a link to the core playlist would be better IMO. Some folks might keep trying to click the topics but wouldn't get redirected anywhere which might get confusing

I added the playlist link as you said in my recent commit b05b759d2a61dbddb9474b8831933817427f9a40

**Comment by Prathamesh2805** [comment]
Is this issue closed or @Aman254 are you still working on it?

**Comment by AnuragThePathak** [comment]
@Prathamesh2805 Aman has completed his part for now, and review is in process.

**Comment by Prathamesh2805** [comment]
Okay cool!
Please let me know if there is anything else where I can help!

**Comment by Aman254** [comment]
@Ridhvisaikasam @siddhant-khisty Now I, think we can close this issue, as its resolved
