### ISSUE TITLE
[bug] website is not responsive for small device

### ISSUE THREAD

**Issue by techmannih** [WeMakeDevs/wemakedevs#721]
### Describe the bug

hello @WeMakeDevs ,
I found an issue in your website " We Make Devs " which is not responsive for iphone 5 gmail id is out of container .please check it .
I want to work on this issue .....please assign me

### Expected Behavior

it is not good for user interface

### Screenshot/ Video

![WhatsApp Image 2023-07-19 at 15 54 01](https://github.com/WeMakeDevs/wemakedevs/assets/125847751/1f05a257-22ec-4699-80b2-0ff010a97fa3)

**Comment by techmannih** [comment]
Hello @AnuragThePathak @siddhant-khisty  ,
 i want to work on it please assign me .

**Comment by siddhant-khisty** [comment]
cc @Chandraprakash-Darji

**Comment by Chandraprakash-Darji** [comment]
@techmannih What is the screen size you are testing?

**Comment by techmannih** [comment]
It's iPhone 5

**Comment by Chandraprakash-Darji** [comment]
@techmannih thank's for reporting it.

**Comment by diva-21** [comment]
Hey @Chandraprakash-Darji ,
Can i take up this issue to solve this if its not yet done..
very much intrested in solving this...

**Comment by AnuragThePathak** [comment]
Hey @diva-21 if you have good knowledge on frontend, do you mind checking whether this issue is still valid or not? As per my observations, it's already done.

**Comment by diva-21** [comment]
> Hey @diva-21 if you have good knowledge on frontend, do you mind checking whether this issue is still valid or not? As per my observations, it's already done.

will check and intimate you. :)

**Comment by diva-21** [comment]
Hey @AnuragThePathak , issue is 

> Hey @diva-21 if you have good knowledge on frontend, do you mind checking whether this issue is still valid or not? As per my observations, it's already done.

Hey @AnuragThePathak , its still there. I solved this ,raising my pr and tested with all the possible mobile screens. Review my pr if possible.

**Comment by PushpakRaut** [comment]
Hey @AnuragThePathak please look into my PR as well if possible.

**Comment by AnuragThePathak** [comment]
@diva-21 @PushpakRaut  do you mind sharing the resolution where the problem occurs?

**Comment by PushpakRaut** [comment]
It was at 320px width which is small mobile size such as iPhone 5, @AnuragThePathak

**Comment by techmannih** [comment]
Hello @AnuragThePathak , 
I raise this issue and I also remember you about this in previous comments ,Which is not responsible in iphone 5 at 320px .please assign me ....
I want to handle this this

**Comment by AnuragThePathak** [comment]
<img width="527" alt="Screen Shot 2023-08-25 at 4 00 25 PM" src="https://github.com/WeMakeDevs/wemakedevs/assets/75429250/8cf122b5-94f0-4988-9371-a3e8e54c5e3b">

@PushpakRaut it barely appears completely. @siddhigate @Parvej2001 suggestion from any of you would be appreciated.

**Comment by AnuragThePathak** [comment]
@techmannih if you have a physical iPhone 5, you may prefer sharing a screenshot from it first.

**Comment by PushpakRaut** [comment]
Yes @AnuragThePathak but if you applied the changes that I made this will also not happen their and I have tested that changes on every device.

**Comment by AnuragThePathak** [comment]
@PushpakRaut ok I understand what you mean. But since we range the responsiveness of websites from smart phones to pcs only, I'll wait for the suggestions of the requested persons.

**Comment by PushpakRaut** [comment]
No problem @AnuragThePathak will wait.

**Comment by diva-21** [comment]
> @diva-21 @PushpakRaut do you mind sharing the resolution where the problem occurs?

hey @AnuragThePathak , the resolution on iPhone5 is 320 x 568.
