### ISSUE TITLE
[bug]Padding bottom of "Join Us" section is way too much

### ISSUE THREAD

**Issue by aaqib605** [WeMakeDevs/wemakedevs#728]
### Describe the bug

 I noticed an issue with the 'Join us' section, where the vertical padding was larger than intended, set at 5rem. After making a simple adjustment and setting only the top padding to 5rem, the design appeared much more appealing and aesthetically pleasing.

### Expected Behavior

Making a simple adjustment and setting only the top padding to 5rem, the design appeared much more appealing and aesthetically pleasing.

### Screenshot/ Video

 
Current padding preview:

**Comment by mhdamaan79** [comment]
I would like to work on this issue, please assign it to me.
@siddhant-khisty @Chandraprakash-Darji

**Comment by aaqib605** [comment]
> I would like to work on this issue, please assign it to me. @siddhant-khisty @Chandraprakash-Darji

I should get to work on this issue if the maintainers @siddhant-khisty  @Chandraprakash-Darji find it to be a valuable enhancement.

**Comment by Chandraprakash-Darji** [comment]
@aaqib605 Share the screenshot

**Comment by Chandraprakash-Darji** [comment]
![Screenshot 2023-08-03 at 10 47 18 AM](https://github.com/WeMakeDevs/wemakedevs/assets/93640141/5069e708-ef77-49dd-b3d8-64be98d44f3f)
Padding is standard on top and bottom. Just that iframe height shows that padding bottom is more

**Comment by aaqib605** [comment]
Padding Top:  
<img width="1440" alt="Screenshot 2023-08-03 at 10 50 47 AM" src="https://github.com/WeMakeDevs/wemakedevs/assets/78491606/f809ffef-9471-4f86-b013-d6c8417a0180">



Padding Bottom:  
<img width="1440" alt="Screenshot 2023-08-03 at 10 50 52 AM" src="https://github.com/WeMakeDevs/wemakedevs/assets/78491606/36e849a4-b670-41bd-a0f3-52b8c7cfd480">
 

I believe even when the card is expanded, the padding-bottom is still not in sync with padding-top:
<img width="1440" alt="Screenshot 2023-08-03 at 11 03 42 AM" src="https://github.com/WeMakeDevs/wemakedevs/assets/78491606/2ae5e3ff-c4cf-467f-a36c-aa5f69a6110c">

**Comment by Chandraprakash-Darji** [comment]
I am saying that iframe creates an illusion of more padding in the bottom than the top. I think this is not a big issue

**Comment by AdityaSrivastava185** [comment]
Hello , I am trying to work on this issues but i am unable to download all the dependencies using the command npm clean-install
Can someone please help me with this issue ??
![Screenshot 2023-08-05 162823](https://github.com/WeMakeDevs/wemakedevs/assets/102461506/891bd27f-fc52-4e88-a40a-23f3aa2ef939)

**Comment by aaqib605** [comment]
Please have a look at how the adjusted padding looks like:
<img width="1440" alt="Screenshot 2023-08-05 at 11 06 52 AM" src="https://github.com/WeMakeDevs/wemakedevs/assets/78491606/2824a7e6-eaba-4a32-93f8-7fc065aeddc6">


@Chandraprakash-Darji If you find the addition valuable, please assign the issue to me. If not, I'm happy to assist as needed. Your guidance is appreciated.

**Comment by Chandraprakash-Darji** [comment]
What padding value you have setted???

**Comment by aaqib605** [comment]
@Chandraprakash-Darji currently padding top and bottom is set to 5rem. 
By setting only the padding top to 5rem makes the design look good.

**Comment by Chandraprakash-Darji** [comment]
Closing this issue:
Reason: The main problem is the iframe size, If we reduce the iframe size then it will make it scrollable
Solution: We are going to implement custom form for these not going to use iframe
