### ISSUE TITLE
when clicking on any of the tracks, it should redirect to the compose page on hashnode [feat]

### ISSUE THREAD

**Issue by Anushka-Bhowmick** [WeMakeDevs/wemakedevs#730]
### Would you like to have a new feature? Please describe.

In the tracks section, the individual tracks can be made accessible by redirecting us to the hashnode website where we would write our blogs.

### How would this feature be beneficial for the project

1.  It would make the website more interactive.
2.  It would help newcomers to go to the blog writing section without much  hassle.

**Comment by aqsaaqeel** [comment]
Can I work on this?

**Comment by siddhant-khisty** [comment]
@AnuragThePathak yes. Tldr; when clicking on any of the tracks, it should redirect to the compose page on hashnode

**Comment by siddhant-khisty** [comment]
@Anushka-Bhowmick please update the tittle of the issue to describe the festure request clearly :)

**Comment by Anushka-Bhowmick** [comment]
sure!

**Comment by AnuragThePathak** [comment]
@aqsaaqeel are you still interested in working?

**Comment by aqsaaqeel** [comment]
yes

**Comment by AnuragThePathak** [comment]
@aqsaaqeel are you still working?

**Comment by Sreejit-Sengupto** [comment]
I have the feature ready. If @aqsaaqeel not working still I can raise a PR then.

**Comment by AnuragThePathak** [comment]
@Sreejit-Sengupto go ahead, @aqsaaqeel is not responding for 2 weeks.

**Comment by Sreejit-Sengupto** [comment]
Done!
