### ISSUE TITLE
Under Testimonials section(Not found)

### ISSUE THREAD

**Issue by parmishh** [WeMakeDevs/wemakedevs#733]
## Current Situation
Under Testimonials section(Not found)
I think Logic must be implemented to prevent this kind of Not Found cases.

Screenshot of  issue below:
![Screenshot (170)](https://github.com/WeMakeDevs/wemakedevs/assets/91942072/c4f3a828-28a8-4a40-b30d-e16842d4e51c)

### To Reproduce

Go to https://wemakedevs.org/courses#testimonials

### Expected Behavior

Logic must be implemented to prevent this kind of Not Found cases.

**Comment by Rajeevjewar** [comment]
> parmishh

Hey @parmishh, I try to find the same tweet on Twitter(Tweet id: 1620081639199244288) but it's not available on the internet, So then what can I do to fix this issue? If you find the correct tweet about the community then please tell me because I want to work on this issue.

**Comment by AnuragThePathak** [comment]
> > parmishh
> 
> Hey @parmishh, I try to find the same tweet on Twitter(Tweet id: 1620081639199244288) but it's not available on the internet, So then what can I do to fix this issue? If you find the correct tweet about the community then please tell me because I want to work on this issue.

@Susmita-Dey you may able to provide some insights.

**Comment by Susmita-Dey** [comment]
Hey @parmishh If the tweet isn't available on Twitter, then it might have been deleted. Just remove the tweetId from our code and it will not show any further error.

**Comment by AnuragThePathak** [comment]
@Rajeevjewar what insights would you like to provide?

**Comment by Rajeevjewar** [comment]
> @Rajeevjewar what insights would you like to provide?

Like we can add another tweet ID replace with the old one.

**Comment by AnuragThePathak** [comment]
Ya sure you can do that since @Susmita-Dey neither seems to have any idea regarding this. Just share the tweet here before updating the code.
