### ISSUE TITLE
subscribe form is having scrollbar on devices below 452px inside a section [bug]

### ISSUE THREAD

**Issue by kedar1998** [WeMakeDevs/wemakedevs#741]
### Describe the bug

The subscribe  section itself is scrollable.

### Expected Behavior

It should not be scrollable inside a section. It should have normal flow.

### Screenshot/ Video

![image](https://github.com/WeMakeDevs/wemakedevs/assets/103363619/6c2a0b99-46f2-4fb9-8613-9b126018b150)

**Comment by kedar1998** [comment]
I am interested is solving this issue. Can you please assign me this issue

**Comment by VineeTagarwaL-code** [comment]
Can i solve this issue , please assign

**Comment by HimanshuMahto** [comment]
Hey @apoorv-on-git @itshypon @anongorax Please the review the PR I have regarding this issue.
