### ISSUE TITLE
[bug] Sometimes testimonials doesn't load up

### ISSUE THREAD

**Issue by thepushpesh** [WeMakeDevs/wemakedevs#743]
### Describe the bug

When we go to the testimonial section there is no testimonials can be seen it's seems like something is loading but nothing happens

### To Reproduce

Go to https://wemakedevs.org/courses#testimonials

### Expected Behavior

Testimonials should show up

### Screenshot/ Video

![testimonial](https://github.com/WeMakeDevs/wemakedevs/assets/60227876/e4bdcccd-af38-4e94-8fb8-edf95b0bf594)

**Comment by AnuragThePathak** [comment]
@thepushpesh can verify once if this problem is fixed now by any chance?

**Comment by thepushpesh** [comment]
Yes @AnuragThePathak now testimonials are showing up.

**Comment by AnuragThePathak** [comment]
Cool
