### ISSUE TITLE
The event button on the banner homepage of should redirect to events section of the homepage.

### ISSUE THREAD

**Issue by Sreejit-Sengupto** [WeMakeDevs/wemakedevs#748]
![MacBook Pro 16_ - 12](https://github.com/WeMakeDevs/wemakedevs/assets/69980616/ac03e0f6-35bc-4172-831e-7dd7a3079aac)
Redirecting the user to events section of the event page would make more sense in my opinion.

**Comment by thejaysharma** [comment]
Hey @Sreejit-Sengupto , I want to work on this issue, can you assign it to me?  :)

**Comment by Sreejit-Sengupto** [comment]
> Hey @Sreejit-Sengupto , I want to work on this issue, can you assign it to me?  :)

Yes let's work on it together

**Comment by theunhackable** [comment]
This Issue doesn't exists on https://wemakedevs.org/ I think this can be closed

**Comment by Anagha-coder** [comment]
@Sreejit-Sengupto Hey, What's the update on this issue?
Is this still open for contribution?

**Comment by Sreejit-Sengupto** [comment]
> @Sreejit-Sengupto Hey, What's the update on this issue?
> Is this still open for contribution? 

The maintainers are yet to approve this issue.

**Comment by Prathamesh2805** [comment]
> @Sreejit-Sengupto Hey, What's the update on this issue? Is this still open for contribution?

That issue doesn't exist on https://wemakedevs.org/ . It need to be closed ig!

**Comment by Sreejit-Sengupto** [comment]
> > @Sreejit-Sengupto Hey, What's the update on this issue? Is this still open for contribution?
> 
> That issue doesn't exist on https://wemakedevs.org/ . It need to be closed ig!

Is the issue resolved. It still doesn't scrolls to events section of the event page

**Comment by Chandraprakash-Darji** [comment]
It is mean to open in new page, not the section

**Comment by Sreejit-Sengupto** [comment]
Ok! I thought redirecting to the events section seemed more meaningful 🤔
