### ISSUE TITLE
Event winners twitter posts are overlapping.

### ISSUE THREAD

**Issue by M0hitReddy** [WeMakeDevs/wemakedevs#761]
### Describe the bug

In event winners section twitter posts are overlapping after width of 770px  and the hidden post cards are visible between gaps of posts.

### Screenshot/ Video

![Screenshot 2023-08-26 143238](https://github.com/WeMakeDevs/wemakedevs/assets/114643178/e583cccf-05bb-46bc-80ce-cde88110e07b)

**Comment by theunhackable** [comment]
I would like to work on this issue. Assign it to me.

**Comment by theunhackable** [comment]
@AnuragThePathak Hey I have worked on the problem and solved it. Can I have the permission to do a PR?
