### ISSUE TITLE
[feat] Feature Request to Make seperate page for Mentorship section

### ISSUE THREAD

**Issue by theunhackable** [WeMakeDevs/wemakedevs#764]
### Would you like to have a new feature? Please describe.

![image](https://github.com/WeMakeDevs/wemakedevs/assets/53367382/d5ff948b-6de0-44f3-8438-1f3927deeecb)

This section currently leads to the GitHub Repo. I would like to propose a seperate endpoint in the website www.wemakedevs.com for this section.

## Goals:

- Make the resource from https://github.com/WeMakeDevs/roadmaps directly available in the website itself.

    - Develop a basic website for displaying all the info on this repositories later can be turned into awesome looking website.
    - Integrate Google and Github authentication service into the website to track users.
    - Make sure the learners can track their progress directly from the website.
    - Create a seperate Project showcase section which is open for the learners to showcase their projects which can be reviewed by other learners

## Future goals
- Develop the documentation to create a beautiful user friendly blog type guide of all the courses using  `.mdx`. These files can be rendered automatically to the website.
    - Provide styled mdx components for the contributors who are interested in documenting the pages.

I would love to lead this but I'm just a junior developer still learning a lot of stuff. But I can dedicate atleast 2hrs a day to this project. I need guidence from seniors and a lot of other devs to make this possible.

### How would this feature be beneficial for the project

The goal of wemakedevs is to give a helping hand to new commers which I loved. I would love to take this website forward to another level.

The main aim of this project is to attract new B.Tech students, people who are looking for a career change or people who know nothing but are interested in Tech and give them guidence on how things should be done.  

### Additional context

The education system sucks. When I joined B.Tech in 2018 I literally know nothing. I always looked for help which I never recieved. I wasted a lot of time just knowing different things by trail and error through internet. By the time I realised what I wanted to do I was in my final year. So I think websites like this can help people like the past me to find their way in Tech industry.

**Comment by Chandraprakash-Darji** [comment]
@theunhackable Thanks for the amazing descriptive suggestion.

We already have the roadmap project https://github.com/WeMakeDevs/roadmap-runner where user can track there progress. 

You can look into it. It is in active from some time
