### ISSUE TITLE
[bug] Regestration problem not found for road-less-travelled event 

### ISSUE THREAD

**Issue by theunhackable** [WeMakeDevs/wemakedevs#769]
### Describe the bug

Form not found and the section for registering to the event shows 404 error

### To Reproduce

go to https://wemakedevs.org/events/road-less-travelled#register

### Expected Behavior

A form needs to appear instead of 404 error

### Screenshot/ Video

![image](https://github.com/WeMakeDevs/wemakedevs/assets/53367382/890afdd2-aae0-4a75-82c9-ae2139a18361)

**Comment by theunhackable** [comment]
@Susmita-Dey  You are working on it right?

**Comment by Susmita-Dey** [comment]
Hey @theunhackable I'm aware of the problem. 

@Chandraprakash-Darji is working on it.
