### ISSUE TITLE
[other] Replace kunal@wemakedevs.org with Email or Mail 

### ISSUE THREAD

**Issue by manzil-infinity180** [WeMakeDevs/wemakedevs#771]
### What would you like to share?

![Screenshot_20230829_211228](https://github.com/WeMakeDevs/wemakedevs/assets/119070053/afeacfb2-a9ae-4046-abb6-61a5a47dbfe1)

**Comment by manzil-infinity180** [comment]
If you want assign it to me

**Comment by AnuragThePathak** [comment]
@siddhant-khisty is this needed?

**Comment by siddhant-khisty** [comment]
I don't think this is needed. Besides, it is a difficult implementation. From my experience, it opens an Email app that is installed on a local PC instead of opening Gmail or whatever mail provider you use.
