### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by Abhi-paul16** [WeMakeDevs/wemakedevs#772]
### Describe the bug

I would like to propose a change to the current Twitter icon. As icons play a significant role in representing the project and creating a visual identity, I believe updating the Twitter icon could enhance the overall aesthetics and recognition of the website.

![WeMakeDevs - Google Chrome 8_30_2023 11_05_41 PM](https://github.com/WeMakeDevs/wemakedevs/assets/68468264/81fa5436-ca44-4b78-b536-bc05a5753ff8)

### Expected Behavior

- Change the old logo with the new one.

**Comment by theunhackable** [comment]
Hey! Our repo uses react-icons to pull those SVG icons. As of now there is no new 𝕏 icon available. The react-icons community suggests to download the twitter 𝕏 logo from https://about.twitter.com/en/who-we-are/brand-toolkit

An issue is raised on updating twitter to new icon on [react-icons repository](https://github.com/react-icons/react-icons/issues/788)

I would like to ask the team about how I should proceed further.
- Wait till new Icon available or
- Create a JSX copmponent temporarily and add the icon

**Comment by maverick-farhan** [comment]
I want to contribute in this issue. Shall I?

**Comment by maverick-farhan** [comment]
Updated the twitter icon to X, would you please review my code. Thanks <3
