### ISSUE TITLE
The scroll bar should be more decorative by changing color and the website needed animation to look more attractive

### ISSUE THREAD

**Issue by harshalhonde21** [WeMakeDevs/wemakedevs#803]
### Would you like to have a new feature? Please describe.

when I visiting the website there is simple scroll bar it should be need to change. And the mainly change is to add the animation because it is very nice to see to users and user will attractive to that website.

### How would this feature be beneficial for the project

This feature is very benefical to project because user always attractive with good thing the number of user/student come in website the animation will attract more towards website.

### Additional context

![ss](https://github.com/WeMakeDevs/wemakedevs/assets/105191619/cbb9bf2f-ecde-4a43-8173-b73fda3df8e3)

**Comment by harshalhonde21** [comment]
please assign this issue to me

**Comment by maverick-farhan** [comment]
Hey amazing folks, i would love to work on this issue. Please assign to me
