### ISSUE TITLE
[bug] Website Link still open on the Same Tab.

### ISSUE THREAD

**Issue by Pravesh-Sudha** [WeMakeDevs/wemakedevs#809]
### Describe the bug

I submitted a PR for opening the link of WeMakeDevs website on a new Page, though PR has been merged but still when you click on the **WeMakeDevs** logo or **Visit** text in the README.md file, it opens the website on the same page rather than a new tab.

### To Reproduce

1. Go to READMEmd
2. Click on **WeMakeDevs logo** or **Visit** text
3. See the website on the same tab

### Expected Behavior

The Website Should open on **New Tab**.

**Comment by Vijaykv5** [comment]
I would love to work on this issue

**Comment by Pravesh-Sudha** [comment]
What would be your approach to solve it...

**Comment by Vijaykv5** [comment]
May be adding {:target="_blank"} will work @Pravesh-Sudha

**Comment by Pravesh-Sudha** [comment]
@Vijaykv5 I have tried that, you can see the Code format of README.md file

**Comment by Pravesh-Sudha** [comment]
That's great @malivinayak, I don't have the authority to assign issue, one of the maintainers will assign you the issue. stay tuned :)

**Comment by Chandanmali** [comment]
@Pravesh-Sudha can you assign me this issue

**Comment by AnuragThePathak** [comment]
It is not possible https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank
