### ISSUE TITLE
[feat] Button Hovering Animation Enhancement

### ISSUE THREAD

**Issue by nishitxmehta** [WeMakeDevs/wemakedevs#810]
### Would you like to have a new feature? Please describe.

This feature will enhance the button hovering animation for all the buttons

This is the original button hovering effect:
![Screen Recording 1](https://github.com/WeMakeDevs/wemakedevs/assets/80708599/de663eb8-c1f1-4f27-bdac-10e6a7d4189b)

This can be the enhanced button hovering effect:
![Screen Recording 2](https://github.com/WeMakeDevs/wemakedevs/assets/80708599/81ccb304-838b-432d-884e-f247130349c5)

_**Note:** The above recording is for demo purpose for enhancing the button hovering effect not the UI change_

### How would this feature be beneficial for the project

This feature will be beneficial as it will enhance the button hovering animation for all the buttons and enhance the user experience.  

### Additional context

Hi @AnuragThePathak, if you consider this enhancement please assign this issue to me.

**Comment by AnuragThePathak** [comment]
Honestly speaking, I personally prefer to keep things simple, so I won't be interested in this enhancement. Feedbacks from @siddhant-khisty and @Susmita-Dey is also appreciated.

**Comment by Susmita-Dey** [comment]
> Honestly speaking, I personally prefer to keep things simple, so I won't be interested in this enhancement. Feedbacks from @siddhant-khisty and @Susmita-Dey is also appreciated.

I agree with you. I don't think this change is needed

**Comment by nishitxmehta** [comment]
Thanks to all for your feedback. I'm closing the issue.
