### ISSUE TITLE
[bug] Implement Multi-Stage Build in Dockerfile

### ISSUE THREAD

**Issue by Saurav-Pant** [WeMakeDevs/wemakedevs#814]
### Describe the bug

The current Dockerfile lacks a multi-stage build. Adding this enhancement significantly reduces the image size, optimizes distribution, and simplifies container management.

### To Reproduce

Go to Dockerfile 
and add this 
`COPY package*.json ./ `     before this line `COPY . .`

**Comment by Koushik1311** [comment]
I would like to work on this issue

**Comment by SaptarshiSarkar12** [comment]
@AnuragThePathak Can I work on this issue?

**Comment by AnuragThePathak** [comment]
@SaptarshiSarkar12 go ahead

**Comment by SaptarshiSarkar12** [comment]
@AnuragThePathak Thank you for assigning this issue to me 😁

**Comment by AnuragThePathak** [comment]
@SaptarshiSarkar12 you should use package*.json then only package-lock.json will be copied

**Comment by SaptarshiSarkar12** [comment]
@AnuragThePathak I was using `npm install` previously. So, if I use `package-lock.json`, then, I also need to change the command to `npm ci`, right?

**Comment by AnuragThePathak** [comment]
Yes you must use `npm ci` else we may see unintended behaviors in production.

**Comment by SaptarshiSarkar12** [comment]
@AnuragThePathak Okay. I have added. Please check #827
