### ISSUE TITLE
[feat] Add scale up animation on hovering the go to top button

### ISSUE THREAD

**Issue by singodiyashubham87** [WeMakeDevs/wemakedevs#820]
### Would you like to have a new feature? Please describe.

I want to add a scale-up animation when the user hovers over the go-to-top button.

### How would this feature be beneficial for the project

This will enhance the user experience.

**Comment by gakshita** [comment]
@AnuragThePathak can you assign this to me?

**Comment by AnuragThePathak** [comment]
@gakshita I can surely assign it you. However, I can't guarantee whether it'll be reviewed/merged or not.

**Comment by Pooja1672** [comment]
Hi @singodiyashubham87 , I would love to work on this issue. Can you please assign it to me?

**Comment by singodiyashubham87** [comment]
@Pooja1672 I'm not the owner of the repository, Miss.
I can't assign the issue to anyone, ask the Project Admin for that.

**Comment by mallyapravin** [comment]
Hi, I am interested in working on this. Please assign it to me.

**Comment by Pooja1672** [comment]
Hi @AnuragThePathak , I would like to work on this issue.. Can you please assign it to me?

**Comment by AnuragThePathak** [comment]
@Pooja1672 I assigned you as you are the first one @mallyapravin
