### ISSUE TITLE
[bug]: Design inconsistency in some static images

### ISSUE THREAD

**Issue by Swpn0neel** [WeMakeDevs/wemakedevs#824]
### Describe the bug

Some static images in the site doesn't have any border radius, while majority of the other boxes have a slight rounded corners, this makes a design inconsistency and I want to implement the border-radius values to those image boxes too, which will enhance user experience through the design consistency of the site.

### To Reproduce

1. Go to https://wemakedevs.org
2. Check the images in the Courses and Mentorship sections

### Expected Behavior

The images in those sections should have rounded corners.

### Screenshot/ Video

![image](https://github.com/WeMakeDevs/wemakedevs/assets/121167506/d0974f22-a27d-45af-8c48-ce62ecd40072)
<br>
![image](https://github.com/WeMakeDevs/wemakedevs/assets/121167506/58d8da2f-0d37-4ec2-92e4-d351ed959783)

**Comment by nsundriyal62** [comment]
if this is a genuine bug or enhancement 
i want to work on this
can you assign this to me?
this is pretty easy i can solve it.

**Comment by Swpn0neel** [comment]
I hope this issue gets assigned to me, cause I've opened it 🙂

**Comment by nsundriyal62** [comment]
ok sir ok 

:)
