### ISSUE TITLE
[bug]:Testimonials content is out of div 

### ISSUE THREAD

**Issue by techmannih** [WeMakeDevs/wemakedevs#828]
### Describe the bug

Hello @AnuragThePathak ,
Testimonials content is out of div  for all small devices. check it asap 
Link:https://wemakedevs.org/courses/dsa
I want to work on this issue... assign me this issue

### Screenshot/ Video

<img width="517" alt="2023-11-21 (2)" src="https://github.com/WeMakeDevs/wemakedevs/assets/125847751/2a86e1f1-ac96-4f05-87a2-eb2404f10e67">

**Comment by AnuragThePathak** [comment]
Sorry for delayed response, you can start working on it.

**Comment by techmannih** [comment]
sure

> Sorry for delayed response, you can start working on it.

sure
