### ISSUE TITLE
[bug] Responsiveness issue on some devices

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [WeMakeDevs/wemakedevs#97]
### Describe the bug

The website is still not responsive for some devices.

### To Reproduce

Use the viewing option of iphone XR, Galaxy S20 ultra etc.. in inspect elements.

### Screenshot/ Video

![MP2](https://user-images.githubusercontent.com/91469717/198869421-ff982b3b-a4d2-49a8-a8d8-12be1ca40849.png)
![MP3](https://user-images.githubusercontent.com/91469717/198869427-61f41840-8d75-4e20-995d-1893801e7d0e.png)

**Comment by SuperAayush** [comment]
Hey @Lakshay-Pruthi, you can start working on this 😄!!

**Comment by Lakshay-Pruthi** [comment]
@SuperAayush issue Resolved #99
